// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeTenantMemberServiceServer is an autogenerated mock type for the UnsafeTenantMemberServiceServer type
type UnsafeTenantMemberServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedTenantMemberServiceServer provides a mock function with given fields:
func (_m *UnsafeTenantMemberServiceServer) mustEmbedUnimplementedTenantMemberServiceServer() {
	_m.Called()
}

// NewUnsafeTenantMemberServiceServer creates a new instance of UnsafeTenantMemberServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeTenantMemberServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeTenantMemberServiceServer {
	mock := &UnsafeTenantMemberServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
