// Code generated by mockery v2.50.4. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeProjectServiceServer is an autogenerated mock type for the UnsafeProjectServiceServer type
type UnsafeProjectServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedProjectServiceServer provides a mock function with no fields
func (_m *UnsafeProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {
	_m.Called()
}

// NewUnsafeProjectServiceServer creates a new instance of UnsafeProjectServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeProjectServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeProjectServiceServer {
	mock := &UnsafeProjectServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
