// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/iam.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IAMConfig struct {
	IssuerConfig         *IssuerConfig         `protobuf:"bytes,1,opt,name=issuer_config,json=issuerConfig,proto3" json:"issuer_config,omitempty"`
	IdmConfig            *IDMConfig            `protobuf:"bytes,2,opt,name=idm_config,json=idmConfig,proto3" json:"idm_config,omitempty"`
	GroupConfig          *NamespaceGroupConfig `protobuf:"bytes,3,opt,name=group_config,json=groupConfig,proto3" json:"group_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IAMConfig) Reset()         { *m = IAMConfig{} }
func (m *IAMConfig) String() string { return proto.CompactTextString(m) }
func (*IAMConfig) ProtoMessage()    {}
func (*IAMConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d513d8b3129389cd, []int{0}
}

func (m *IAMConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IAMConfig.Unmarshal(m, b)
}
func (m *IAMConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IAMConfig.Marshal(b, m, deterministic)
}
func (m *IAMConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IAMConfig.Merge(m, src)
}
func (m *IAMConfig) XXX_Size() int {
	return xxx_messageInfo_IAMConfig.Size(m)
}
func (m *IAMConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IAMConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IAMConfig proto.InternalMessageInfo

func (m *IAMConfig) GetIssuerConfig() *IssuerConfig {
	if m != nil {
		return m.IssuerConfig
	}
	return nil
}

func (m *IAMConfig) GetIdmConfig() *IDMConfig {
	if m != nil {
		return m.IdmConfig
	}
	return nil
}

func (m *IAMConfig) GetGroupConfig() *NamespaceGroupConfig {
	if m != nil {
		return m.GroupConfig
	}
	return nil
}

type IssuerConfig struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ClientId             string   `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IssuerConfig) Reset()         { *m = IssuerConfig{} }
func (m *IssuerConfig) String() string { return proto.CompactTextString(m) }
func (*IssuerConfig) ProtoMessage()    {}
func (*IssuerConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d513d8b3129389cd, []int{1}
}

func (m *IssuerConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IssuerConfig.Unmarshal(m, b)
}
func (m *IssuerConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IssuerConfig.Marshal(b, m, deterministic)
}
func (m *IssuerConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssuerConfig.Merge(m, src)
}
func (m *IssuerConfig) XXX_Size() int {
	return xxx_messageInfo_IssuerConfig.Size(m)
}
func (m *IssuerConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IssuerConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IssuerConfig proto.InternalMessageInfo

func (m *IssuerConfig) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IssuerConfig) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

// mandatory config
type IDMConfig struct {
	IdmType string `protobuf:"bytes,1,opt,name=idm_type,json=idmType,proto3" json:"idm_type,omitempty"`
	// optional
	ConnectorConfig      *ConnectorConfig `protobuf:"bytes,2,opt,name=connector_config,json=connectorConfig,proto3" json:"connector_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *IDMConfig) Reset()         { *m = IDMConfig{} }
func (m *IDMConfig) String() string { return proto.CompactTextString(m) }
func (*IDMConfig) ProtoMessage()    {}
func (*IDMConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d513d8b3129389cd, []int{2}
}

func (m *IDMConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDMConfig.Unmarshal(m, b)
}
func (m *IDMConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDMConfig.Marshal(b, m, deterministic)
}
func (m *IDMConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDMConfig.Merge(m, src)
}
func (m *IDMConfig) XXX_Size() int {
	return xxx_messageInfo_IDMConfig.Size(m)
}
func (m *IDMConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_IDMConfig.DiscardUnknown(m)
}

var xxx_messageInfo_IDMConfig proto.InternalMessageInfo

func (m *IDMConfig) GetIdmType() string {
	if m != nil {
		return m.IdmType
	}
	return ""
}

func (m *IDMConfig) GetConnectorConfig() *ConnectorConfig {
	if m != nil {
		return m.ConnectorConfig
	}
	return nil
}

// Config for group-rolebinding-controller
type NamespaceGroupConfig struct {
	// no action is taken or any namespace in this list
	ExcludedNamespaces string `protobuf:"bytes,1,opt,name=excluded_namespaces,json=excludedNamespaces,proto3" json:"excluded_namespaces,omitempty"`
	// for each element a RoleBinding is created in any Namespace - ClusterRoles are bound with this name
	// admin,edit,view
	ExpectedGroupsList string `protobuf:"bytes,2,opt,name=expected_groups_list,json=expectedGroupsList,proto3" json:"expected_groups_list,omitempty"`
	// Maximum length of namespace-part in clusterGroupname and therefore in the corresponding groupname in the directory.
	// 20 chars für AD, given the naming-conventions
	NamespaceMaxLength int32 `protobuf:"varint,3,opt,name=namespace_max_length,json=namespaceMaxLength,proto3" json:"namespace_max_length,omitempty"`
	// The created RoleBindings will reference this group (from token).
	// oidc:{{ .Namespace }}-{{ .Group }}
	ClusterGroupnameTemplate string `protobuf:"bytes,4,opt,name=cluster_groupname_template,json=clusterGroupnameTemplate,proto3" json:"cluster_groupname_template,omitempty"`
	// The RoleBindings will created with this name.
	// oidc-{{ .Namespace }}-{{ .Group }}
	RolebindingNameTemplate string   `protobuf:"bytes,5,opt,name=rolebinding_name_template,json=rolebindingNameTemplate,proto3" json:"rolebinding_name_template,omitempty"`
	XXX_NoUnkeyedLiteral    struct{} `json:"-"`
	XXX_unrecognized        []byte   `json:"-"`
	XXX_sizecache           int32    `json:"-"`
}

func (m *NamespaceGroupConfig) Reset()         { *m = NamespaceGroupConfig{} }
func (m *NamespaceGroupConfig) String() string { return proto.CompactTextString(m) }
func (*NamespaceGroupConfig) ProtoMessage()    {}
func (*NamespaceGroupConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d513d8b3129389cd, []int{3}
}

func (m *NamespaceGroupConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NamespaceGroupConfig.Unmarshal(m, b)
}
func (m *NamespaceGroupConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NamespaceGroupConfig.Marshal(b, m, deterministic)
}
func (m *NamespaceGroupConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NamespaceGroupConfig.Merge(m, src)
}
func (m *NamespaceGroupConfig) XXX_Size() int {
	return xxx_messageInfo_NamespaceGroupConfig.Size(m)
}
func (m *NamespaceGroupConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_NamespaceGroupConfig.DiscardUnknown(m)
}

var xxx_messageInfo_NamespaceGroupConfig proto.InternalMessageInfo

func (m *NamespaceGroupConfig) GetExcludedNamespaces() string {
	if m != nil {
		return m.ExcludedNamespaces
	}
	return ""
}

func (m *NamespaceGroupConfig) GetExpectedGroupsList() string {
	if m != nil {
		return m.ExpectedGroupsList
	}
	return ""
}

func (m *NamespaceGroupConfig) GetNamespaceMaxLength() int32 {
	if m != nil {
		return m.NamespaceMaxLength
	}
	return 0
}

func (m *NamespaceGroupConfig) GetClusterGroupnameTemplate() string {
	if m != nil {
		return m.ClusterGroupnameTemplate
	}
	return ""
}

func (m *NamespaceGroupConfig) GetRolebindingNameTemplate() string {
	if m != nil {
		return m.RolebindingNameTemplate
	}
	return ""
}

// optional config if idm webhook is used to automatically create/delete groups/roles in the tenant idm
type ConnectorConfig struct {
	// the following are all mandatory
	IdmApiUrl      string `protobuf:"bytes,1,opt,name=idm_api_url,json=idmApiUrl,proto3" json:"idm_api_url,omitempty"`
	IdmApiUser     string `protobuf:"bytes,2,opt,name=idm_api_user,json=idmApiUser,proto3" json:"idm_api_user,omitempty"`
	IdmApiPassword string `protobuf:"bytes,3,opt,name=idm_api_password,json=idmApiPassword,proto3" json:"idm_api_password,omitempty"`
	IdmSystemId    string `protobuf:"bytes,4,opt,name=idm_system_id,json=idmSystemId,proto3" json:"idm_system_id,omitempty"`
	IdmAccessCode  string `protobuf:"bytes,5,opt,name=idm_access_code,json=idmAccessCode,proto3" json:"idm_access_code,omitempty"`
	IdmCustomerId  string `protobuf:"bytes,6,opt,name=idm_customer_id,json=idmCustomerId,proto3" json:"idm_customer_id,omitempty"`
	IdmGroupOu     string `protobuf:"bytes,7,opt,name=idm_group_ou,json=idmGroupOu,proto3" json:"idm_group_ou,omitempty"`
	// optional
	IdmGroupnameTemplate *wrappers.StringValue `protobuf:"bytes,8,opt,name=idm_groupname_template,json=idmGroupnameTemplate,proto3" json:"idm_groupname_template,omitempty"`
	IdmDomainName        string                `protobuf:"bytes,9,opt,name=idm_domain_name,json=idmDomainName,proto3" json:"idm_domain_name,omitempty"`
	IdmTenantPrefix      string                `protobuf:"bytes,10,opt,name=idm_tenant_prefix,json=idmTenantPrefix,proto3" json:"idm_tenant_prefix,omitempty"`
	IdmSubmitter         string                `protobuf:"bytes,11,opt,name=idm_submitter,json=idmSubmitter,proto3" json:"idm_submitter,omitempty"`
	IdmJobInfo           string                `protobuf:"bytes,12,opt,name=idm_job_info,json=idmJobInfo,proto3" json:"idm_job_info,omitempty"`
	IdmReqSystem         string                `protobuf:"bytes,13,opt,name=idm_req_system,json=idmReqSystem,proto3" json:"idm_req_system,omitempty"`
	IdmReqUser           string                `protobuf:"bytes,14,opt,name=idm_req_user,json=idmReqUser,proto3" json:"idm_req_user,omitempty"`
	IdmReqEmail          string                `protobuf:"bytes,15,opt,name=idm_req_email,json=idmReqEmail,proto3" json:"idm_req_email,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ConnectorConfig) Reset()         { *m = ConnectorConfig{} }
func (m *ConnectorConfig) String() string { return proto.CompactTextString(m) }
func (*ConnectorConfig) ProtoMessage()    {}
func (*ConnectorConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_d513d8b3129389cd, []int{4}
}

func (m *ConnectorConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConnectorConfig.Unmarshal(m, b)
}
func (m *ConnectorConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConnectorConfig.Marshal(b, m, deterministic)
}
func (m *ConnectorConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConnectorConfig.Merge(m, src)
}
func (m *ConnectorConfig) XXX_Size() int {
	return xxx_messageInfo_ConnectorConfig.Size(m)
}
func (m *ConnectorConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ConnectorConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ConnectorConfig proto.InternalMessageInfo

func (m *ConnectorConfig) GetIdmApiUrl() string {
	if m != nil {
		return m.IdmApiUrl
	}
	return ""
}

func (m *ConnectorConfig) GetIdmApiUser() string {
	if m != nil {
		return m.IdmApiUser
	}
	return ""
}

func (m *ConnectorConfig) GetIdmApiPassword() string {
	if m != nil {
		return m.IdmApiPassword
	}
	return ""
}

func (m *ConnectorConfig) GetIdmSystemId() string {
	if m != nil {
		return m.IdmSystemId
	}
	return ""
}

func (m *ConnectorConfig) GetIdmAccessCode() string {
	if m != nil {
		return m.IdmAccessCode
	}
	return ""
}

func (m *ConnectorConfig) GetIdmCustomerId() string {
	if m != nil {
		return m.IdmCustomerId
	}
	return ""
}

func (m *ConnectorConfig) GetIdmGroupOu() string {
	if m != nil {
		return m.IdmGroupOu
	}
	return ""
}

func (m *ConnectorConfig) GetIdmGroupnameTemplate() *wrappers.StringValue {
	if m != nil {
		return m.IdmGroupnameTemplate
	}
	return nil
}

func (m *ConnectorConfig) GetIdmDomainName() string {
	if m != nil {
		return m.IdmDomainName
	}
	return ""
}

func (m *ConnectorConfig) GetIdmTenantPrefix() string {
	if m != nil {
		return m.IdmTenantPrefix
	}
	return ""
}

func (m *ConnectorConfig) GetIdmSubmitter() string {
	if m != nil {
		return m.IdmSubmitter
	}
	return ""
}

func (m *ConnectorConfig) GetIdmJobInfo() string {
	if m != nil {
		return m.IdmJobInfo
	}
	return ""
}

func (m *ConnectorConfig) GetIdmReqSystem() string {
	if m != nil {
		return m.IdmReqSystem
	}
	return ""
}

func (m *ConnectorConfig) GetIdmReqUser() string {
	if m != nil {
		return m.IdmReqUser
	}
	return ""
}

func (m *ConnectorConfig) GetIdmReqEmail() string {
	if m != nil {
		return m.IdmReqEmail
	}
	return ""
}

func init() {
	proto.RegisterType((*IAMConfig)(nil), "v1.IAMConfig")
	proto.RegisterType((*IssuerConfig)(nil), "v1.IssuerConfig")
	proto.RegisterType((*IDMConfig)(nil), "v1.IDMConfig")
	proto.RegisterType((*NamespaceGroupConfig)(nil), "v1.NamespaceGroupConfig")
	proto.RegisterType((*ConnectorConfig)(nil), "v1.ConnectorConfig")
}

func init() {
	proto.RegisterFile("v1/iam.proto", fileDescriptor_d513d8b3129389cd)
}

var fileDescriptor_d513d8b3129389cd = []byte{
	// 683 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0xdb, 0x6e, 0xdb, 0x38,
	0x10, 0x86, 0x91, 0x73, 0x44, 0xdb, 0xb1, 0x97, 0x09, 0x76, 0x95, 0xec, 0x22, 0x08, 0xbc, 0x8b,
	0x45, 0x50, 0x14, 0x76, 0xd3, 0xa2, 0x37, 0x3d, 0x01, 0x81, 0x53, 0x04, 0x2e, 0x92, 0x34, 0x50,
	0xd2, 0xde, 0x0a, 0xb2, 0x38, 0x56, 0x59, 0x48, 0xa4, 0x4c, 0x52, 0x89, 0xf3, 0x40, 0xbd, 0xec,
	0xab, 0xf5, 0x19, 0x0a, 0x8e, 0x48, 0xc5, 0x2e, 0x7a, 0x27, 0xfd, 0xf3, 0xcd, 0x70, 0x66, 0x7e,
	0x92, 0xb4, 0xef, 0x4e, 0x86, 0x3c, 0x29, 0x06, 0xa5, 0x92, 0x46, 0xd2, 0xd5, 0xbb, 0x93, 0x83,
	0xc3, 0x4c, 0xca, 0x2c, 0x87, 0x21, 0x2a, 0x93, 0x6a, 0x3a, 0xbc, 0x57, 0x49, 0x59, 0x82, 0xd2,
	0x35, 0xd3, 0xff, 0xbe, 0x42, 0x82, 0xf1, 0xe9, 0xe5, 0x48, 0x8a, 0x29, 0xcf, 0xe8, 0x4b, 0xd2,
	0xe1, 0x5a, 0x57, 0xa0, 0xe2, 0x14, 0x85, 0x70, 0xe5, 0x68, 0xe5, 0xb8, 0xf5, 0xbc, 0x37, 0xb8,
	0x3b, 0x19, 0x8c, 0x31, 0x50, 0x83, 0x51, 0x9b, 0x2f, 0xfc, 0xd1, 0xa7, 0x84, 0x70, 0x56, 0xf8,
	0x9c, 0x55, 0xcc, 0xe9, 0x60, 0xce, 0x99, 0xab, 0x1c, 0x05, 0x9c, 0x15, 0x8e, 0x7e, 0x4d, 0xda,
	0x99, 0x92, 0x55, 0xe9, 0xf9, 0x35, 0xe4, 0x43, 0xcb, 0x5f, 0x25, 0x05, 0xe8, 0x32, 0x49, 0xe1,
	0xdc, 0x02, 0x2e, 0xb5, 0x95, 0x3d, 0xfe, 0xf4, 0xdf, 0x92, 0xf6, 0x62, 0x23, 0xb4, 0x47, 0xd6,
	0x2a, 0x95, 0x63, 0x9f, 0x41, 0x64, 0x3f, 0xe9, 0xdf, 0x24, 0x48, 0x73, 0x0e, 0xc2, 0xc4, 0x9c,
	0x61, 0x2f, 0x41, 0xb4, 0x5d, 0x0b, 0x63, 0xd6, 0x9f, 0x92, 0xa0, 0xe9, 0x89, 0xee, 0x93, 0x6d,
	0xdb, 0xb6, 0x79, 0x28, 0xc1, 0x15, 0xd8, 0xe2, 0xac, 0xb8, 0x7d, 0x28, 0x81, 0xbe, 0x23, 0xbd,
	0x54, 0x0a, 0x01, 0xa9, 0x91, 0x6a, 0x79, 0xae, 0x5d, 0xdb, 0xe7, 0xc8, 0xc7, 0x5c, 0x8b, 0xdd,
	0x74, 0x59, 0xe8, 0x7f, 0x5b, 0x25, 0x7b, 0xbf, 0x1b, 0x86, 0x0e, 0xc9, 0x2e, 0xcc, 0xd3, 0xbc,
	0x62, 0xc0, 0x62, 0xe1, 0x01, 0xed, 0x8e, 0xa7, 0x3e, 0xd4, 0xa4, 0x6a, 0xfa, 0x8c, 0xec, 0xc1,
	0xbc, 0x84, 0xd4, 0x00, 0x8b, 0x71, 0x11, 0x3a, 0xce, 0xb9, 0x36, 0x6e, 0x32, 0xea, 0x63, 0x78,
	0x86, 0xbe, 0xe0, 0xda, 0xd8, 0x8c, 0xa6, 0x72, 0x5c, 0x24, 0xf3, 0x38, 0x07, 0x91, 0x99, 0x2f,
	0xb8, 0xe7, 0x8d, 0x88, 0x36, 0xb1, 0xcb, 0x64, 0x7e, 0x81, 0x11, 0xfa, 0x86, 0x1c, 0xa4, 0x79,
	0xa5, 0x0d, 0xa8, 0xfa, 0x08, 0x8b, 0xc4, 0x06, 0x8a, 0x32, 0x4f, 0x0c, 0x84, 0xeb, 0x78, 0x52,
	0xe8, 0x88, 0x73, 0x0f, 0xdc, 0xba, 0x38, 0x7d, 0x45, 0xf6, 0x95, 0xcc, 0x61, 0xc2, 0x05, 0xe3,
	0x22, 0x8b, 0x97, 0x93, 0x37, 0x30, 0xf9, 0xaf, 0x05, 0xe0, 0x6a, 0x21, 0xb7, 0xff, 0x63, 0x9d,
	0x74, 0x7f, 0x59, 0x26, 0x3d, 0x24, 0x2d, 0x6b, 0x4b, 0x52, 0xf2, 0xf8, 0xd1, 0x5a, 0x7b, 0x7f,
	0x4e, 0x4b, 0xfe, 0x49, 0xe5, 0xf4, 0x88, 0xb4, 0x9b, 0xb8, 0x06, 0xe5, 0x36, 0x41, 0x1c, 0xa0,
	0x41, 0xd1, 0x63, 0xd2, 0xf3, 0x44, 0x99, 0x68, 0x7d, 0x2f, 0x15, 0xc3, 0xe9, 0x83, 0x68, 0xa7,
	0xa6, 0xae, 0x9d, 0x4a, 0xfb, 0xa4, 0x63, 0x49, 0xfd, 0xa0, 0x0d, 0x14, 0xf6, 0xc2, 0xd4, 0xc3,
	0xda, 0x06, 0x6e, 0x50, 0x1b, 0x33, 0xfa, 0x3f, 0xe9, 0x62, 0xb5, 0x34, 0x05, 0xad, 0xe3, 0x54,
	0x32, 0x3f, 0x95, 0x4d, 0x3d, 0x45, 0x75, 0x24, 0x19, 0x78, 0x2e, 0xad, 0xb4, 0x91, 0x05, 0x28,
	0x5b, 0x6d, 0xb3, 0xe1, 0x46, 0x4e, 0x1d, 0x33, 0xdf, 0x7f, 0xfd, 0x06, 0x64, 0x15, 0x6e, 0x35,
	0xfd, 0xe3, 0x6e, 0x3f, 0x56, 0x34, 0x22, 0x7f, 0x36, 0xc4, 0xf2, 0x3a, 0xb7, 0xf1, 0x0e, 0xfe,
	0x33, 0xa8, 0x5f, 0xf5, 0xc0, 0xbf, 0xea, 0xc1, 0x8d, 0x51, 0x5c, 0x64, 0x9f, 0x93, 0xbc, 0x82,
	0x68, 0xcf, 0x57, 0x5a, 0x72, 0xc9, 0x75, 0xc7, 0x64, 0x91, 0x70, 0x81, 0x26, 0x85, 0x41, 0xd3,
	0xdd, 0x19, 0xaa, 0xd6, 0x19, 0xfa, 0x84, 0xfc, 0x81, 0x8f, 0x02, 0x44, 0x22, 0x4c, 0x5c, 0x2a,
	0x98, 0xf2, 0x79, 0x48, 0x90, 0xb4, 0x05, 0x6e, 0x51, 0xbf, 0x46, 0x99, 0xfe, 0xeb, 0xb6, 0x57,
	0x4d, 0x0a, 0x6e, 0x0c, 0xa8, 0xb0, 0x85, 0x9c, 0x1d, 0xef, 0xc6, 0x6b, 0x7e, 0xdc, 0xaf, 0x72,
	0x12, 0x73, 0x31, 0x95, 0x61, 0xbb, 0x19, 0xf7, 0x83, 0x9c, 0x8c, 0xc5, 0x54, 0xd2, 0xff, 0x88,
	0xb5, 0x25, 0x56, 0x30, 0x73, 0x46, 0x84, 0x9d, 0xa6, 0x4e, 0x04, 0xb3, 0xda, 0x08, 0x5f, 0xc7,
	0x52, 0x68, 0xfb, 0x4e, 0x53, 0x27, 0x82, 0x19, 0xda, 0xee, 0xcc, 0xb4, 0x04, 0x14, 0x09, 0xcf,
	0xc3, 0x6e, 0x63, 0x66, 0x04, 0xb3, 0xf7, 0x56, 0x9a, 0x6c, 0xe2, 0xca, 0x5e, 0xfc, 0x0c, 0x00,
	0x00, 0xff, 0xff, 0xf5, 0x74, 0x29, 0x21, 0x2a, 0x05, 0x00, 0x00,
}
