// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/project.proto

package v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Project is the database model
type Project struct {
	Meta                 *Meta     `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Name                 string    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TenantId             string    `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Quotas               *QuotaSet `protobuf:"bytes,5,opt,name=quotas,proto3" json:"quotas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{0}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetMeta() *Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *Project) GetQuotas() *QuotaSet {
	if m != nil {
		return m.Quotas
	}
	return nil
}

type ProjectCreateRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectCreateRequest) Reset()         { *m = ProjectCreateRequest{} }
func (m *ProjectCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectCreateRequest) ProtoMessage()    {}
func (*ProjectCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{1}
}

func (m *ProjectCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectCreateRequest.Unmarshal(m, b)
}
func (m *ProjectCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectCreateRequest.Marshal(b, m, deterministic)
}
func (m *ProjectCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectCreateRequest.Merge(m, src)
}
func (m *ProjectCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectCreateRequest.Size(m)
}
func (m *ProjectCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectCreateRequest proto.InternalMessageInfo

func (m *ProjectCreateRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ProjectUpdateRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectUpdateRequest) Reset()         { *m = ProjectUpdateRequest{} }
func (m *ProjectUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectUpdateRequest) ProtoMessage()    {}
func (*ProjectUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{2}
}

func (m *ProjectUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectUpdateRequest.Unmarshal(m, b)
}
func (m *ProjectUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectUpdateRequest.Marshal(b, m, deterministic)
}
func (m *ProjectUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectUpdateRequest.Merge(m, src)
}
func (m *ProjectUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectUpdateRequest.Size(m)
}
func (m *ProjectUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectUpdateRequest proto.InternalMessageInfo

func (m *ProjectUpdateRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ProjectDeleteRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectDeleteRequest) Reset()         { *m = ProjectDeleteRequest{} }
func (m *ProjectDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectDeleteRequest) ProtoMessage()    {}
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{3}
}

func (m *ProjectDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectDeleteRequest.Unmarshal(m, b)
}
func (m *ProjectDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ProjectDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectDeleteRequest.Merge(m, src)
}
func (m *ProjectDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectDeleteRequest.Size(m)
}
func (m *ProjectDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectDeleteRequest proto.InternalMessageInfo

func (m *ProjectDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectGetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectGetRequest) Reset()         { *m = ProjectGetRequest{} }
func (m *ProjectGetRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectGetRequest) ProtoMessage()    {}
func (*ProjectGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{4}
}

func (m *ProjectGetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectGetRequest.Unmarshal(m, b)
}
func (m *ProjectGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectGetRequest.Marshal(b, m, deterministic)
}
func (m *ProjectGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectGetRequest.Merge(m, src)
}
func (m *ProjectGetRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectGetRequest.Size(m)
}
func (m *ProjectGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectGetRequest proto.InternalMessageInfo

func (m *ProjectGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectFindRequest struct {
	Id                   *wrappers.StringValue `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          *wrappers.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TenantId             *wrappers.StringValue `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ProjectFindRequest) Reset()         { *m = ProjectFindRequest{} }
func (m *ProjectFindRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectFindRequest) ProtoMessage()    {}
func (*ProjectFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{5}
}

func (m *ProjectFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectFindRequest.Unmarshal(m, b)
}
func (m *ProjectFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectFindRequest.Marshal(b, m, deterministic)
}
func (m *ProjectFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectFindRequest.Merge(m, src)
}
func (m *ProjectFindRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectFindRequest.Size(m)
}
func (m *ProjectFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectFindRequest proto.InternalMessageInfo

func (m *ProjectFindRequest) GetId() *wrappers.StringValue {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ProjectFindRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *ProjectFindRequest) GetDescription() *wrappers.StringValue {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *ProjectFindRequest) GetTenantId() *wrappers.StringValue {
	if m != nil {
		return m.TenantId
	}
	return nil
}

type ProjectResponse struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectResponse) Reset()         { *m = ProjectResponse{} }
func (m *ProjectResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectResponse) ProtoMessage()    {}
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{6}
}

func (m *ProjectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectResponse.Unmarshal(m, b)
}
func (m *ProjectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectResponse.Marshal(b, m, deterministic)
}
func (m *ProjectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectResponse.Merge(m, src)
}
func (m *ProjectResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectResponse.Size(m)
}
func (m *ProjectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectResponse proto.InternalMessageInfo

func (m *ProjectResponse) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type ProjectListResponse struct {
	Projects             []*Project `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ProjectListResponse) Reset()         { *m = ProjectListResponse{} }
func (m *ProjectListResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectListResponse) ProtoMessage()    {}
func (*ProjectListResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37dd3eae429dd876, []int{7}
}

func (m *ProjectListResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectListResponse.Unmarshal(m, b)
}
func (m *ProjectListResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectListResponse.Marshal(b, m, deterministic)
}
func (m *ProjectListResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectListResponse.Merge(m, src)
}
func (m *ProjectListResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectListResponse.Size(m)
}
func (m *ProjectListResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectListResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectListResponse proto.InternalMessageInfo

func (m *ProjectListResponse) GetProjects() []*Project {
	if m != nil {
		return m.Projects
	}
	return nil
}

func init() {
	proto.RegisterType((*Project)(nil), "v1.Project")
	proto.RegisterType((*ProjectCreateRequest)(nil), "v1.ProjectCreateRequest")
	proto.RegisterType((*ProjectUpdateRequest)(nil), "v1.ProjectUpdateRequest")
	proto.RegisterType((*ProjectDeleteRequest)(nil), "v1.ProjectDeleteRequest")
	proto.RegisterType((*ProjectGetRequest)(nil), "v1.ProjectGetRequest")
	proto.RegisterType((*ProjectFindRequest)(nil), "v1.ProjectFindRequest")
	proto.RegisterType((*ProjectResponse)(nil), "v1.ProjectResponse")
	proto.RegisterType((*ProjectListResponse)(nil), "v1.ProjectListResponse")
}

func init() { proto.RegisterFile("v1/project.proto", fileDescriptor_37dd3eae429dd876) }

var fileDescriptor_37dd3eae429dd876 = []byte{
	// 458 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x95, 0xb4, 0x74, 0xda, 0x5b, 0x28, 0xe0, 0xe1, 0x27, 0x0a, 0x23, 0x14, 0x85, 0xbf,
	0x59, 0xa0, 0x84, 0x94, 0xc5, 0xc0, 0x82, 0xd9, 0x80, 0x18, 0x21, 0x81, 0x34, 0xa4, 0x82, 0x2d,
	0xca, 0x34, 0x97, 0xca, 0xa8, 0x13, 0x67, 0x6c, 0x27, 0xbc, 0x0e, 0x3b, 0x1e, 0x8f, 0x57, 0x40,
	0xb1, 0x9d, 0xd4, 0x19, 0x28, 0x65, 0x97, 0xdc, 0x73, 0x3e, 0x5f, 0xcb, 0xe7, 0xc0, 0x8d, 0x3a,
	0x89, 0x4b, 0xce, 0xbe, 0xe1, 0x52, 0x46, 0x25, 0x67, 0x92, 0x11, 0xb7, 0x4e, 0xfc, 0x6b, 0x75,
	0x12, 0x9f, 0xa3, 0xcc, 0xf4, 0xc8, 0x9f, 0xd5, 0x49, 0x7c, 0x51, 0xb1, 0xee, 0xff, 0xfe, 0x8a,
	0xb1, 0xd5, 0x1a, 0x63, 0xf5, 0x77, 0x56, 0x7d, 0x8d, 0xbf, 0xf3, 0xac, 0x2c, 0x91, 0x0b, 0xad,
	0x87, 0x3f, 0x1c, 0xd8, 0x3b, 0xd5, 0x87, 0x92, 0x03, 0x18, 0x36, 0x27, 0x79, 0x4e, 0xe0, 0x1c,
	0x4e, 0xe7, 0xe3, 0xa8, 0x4e, 0xa2, 0x0f, 0x28, 0xb3, 0x54, 0x4d, 0x09, 0x81, 0x61, 0x91, 0x9d,
	0xa3, 0xe7, 0x06, 0xce, 0xe1, 0x24, 0x55, 0xdf, 0x24, 0x80, 0x69, 0x8e, 0x62, 0xc9, 0x69, 0x29,
	0x29, 0x2b, 0xbc, 0x81, 0x92, 0xec, 0x11, 0xb9, 0x07, 0x13, 0x89, 0x45, 0x56, 0xc8, 0x2f, 0x34,
	0xf7, 0x86, 0x4a, 0x1f, 0xeb, 0xc1, 0xbb, 0x9c, 0x3c, 0x84, 0x91, 0xba, 0xab, 0xf0, 0xae, 0xa8,
	0x95, 0x57, 0x9b, 0x95, 0x1f, 0x9b, 0xc9, 0x02, 0x65, 0x6a, 0xb4, 0xf0, 0x15, 0xdc, 0x32, 0x37,
	0x7c, 0xcd, 0x31, 0x93, 0x98, 0xe2, 0x45, 0x85, 0x42, 0x92, 0x47, 0xb0, 0x67, 0x9e, 0xc3, 0xdc,
	0x78, 0xda, 0xe0, 0xc6, 0x9a, 0xb6, 0x9a, 0x85, 0x7f, 0x2a, 0xf3, 0x3e, 0x7e, 0xfa, 0x0f, 0xdc,
	0x7c, 0x84, 0x8f, 0x3b, 0xfc, 0x0d, 0xae, 0x71, 0x83, 0xcf, 0xc0, 0xa5, 0xb9, 0x22, 0x27, 0xa9,
	0x4b, 0xf3, 0xf0, 0x01, 0xdc, 0x34, 0xbe, 0x13, 0x94, 0xdb, 0x4c, 0xbf, 0x1c, 0x20, 0xc6, 0xf5,
	0x96, 0x16, 0x79, 0x6b, 0x7b, 0xda, 0xd9, 0xa6, 0xf3, 0x83, 0x48, 0x27, 0x16, 0xb5, 0x89, 0x45,
	0x0b, 0xc9, 0x69, 0xb1, 0xfa, 0x9c, 0xad, 0x2b, 0x6c, 0x0e, 0x21, 0xcf, 0xac, 0x20, 0x76, 0xf9,
	0x75, 0x4c, 0xc7, 0x7f, 0xc6, 0xb4, 0x0b, 0xec, 0x85, 0xf8, 0xf2, 0x72, 0x88, 0xbb, 0xe8, 0x2e,
	0xe2, 0xf0, 0x05, 0x5c, 0x6f, 0x9f, 0x14, 0x45, 0xc9, 0x0a, 0x81, 0xff, 0x9b, 0xdb, 0x31, 0xec,
	0x9b, 0xd9, 0x7b, 0x2a, 0x36, 0xf4, 0x13, 0x18, 0x1b, 0x87, 0xf0, 0x9c, 0x60, 0x70, 0x19, 0xef,
	0xc4, 0xf9, 0x4f, 0x17, 0x66, 0x66, 0xba, 0x40, 0x5e, 0xd3, 0x25, 0x92, 0x23, 0x18, 0xe9, 0x0a,
	0x11, 0xcf, 0x62, 0x7a, 0xad, 0xf2, 0xf7, 0xed, 0xd3, 0xda, 0xa5, 0x47, 0x30, 0xd2, 0xe5, 0xe9,
	0x81, 0xbd, 0x3e, 0x6d, 0x05, 0x75, 0x6d, 0x7a, 0x60, 0xaf, 0x49, 0x7f, 0x07, 0x13, 0x18, 0x9c,
	0xa0, 0x24, 0xb7, 0x2d, 0x6d, 0xd3, 0xab, 0x6d, 0xbb, 0x86, 0x4d, 0xa9, 0xc8, 0x1d, 0x4b, 0xb4,
	0x5a, 0xe6, 0xdf, 0xb5, 0xe6, 0xf6, 0x93, 0x9e, 0x8d, 0x54, 0x86, 0xcf, 0x7f, 0x07, 0x00, 0x00,
	0xff, 0xff, 0xd5, 0x5b, 0x88, 0x64, 0x61, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProjectServiceClient is the client API for ProjectService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProjectServiceClient interface {
	Create(ctx context.Context, in *ProjectCreateRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	Update(ctx context.Context, in *ProjectUpdateRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	Delete(ctx context.Context, in *ProjectDeleteRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	Get(ctx context.Context, in *ProjectGetRequest, opts ...grpc.CallOption) (*ProjectResponse, error)
	Find(ctx context.Context, in *ProjectFindRequest, opts ...grpc.CallOption) (*ProjectListResponse, error)
}

type projectServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProjectServiceClient(cc grpc.ClientConnInterface) ProjectServiceClient {
	return &projectServiceClient{cc}
}

func (c *projectServiceClient) Create(ctx context.Context, in *ProjectCreateRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, "/v1.ProjectService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Update(ctx context.Context, in *ProjectUpdateRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, "/v1.ProjectService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Delete(ctx context.Context, in *ProjectDeleteRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, "/v1.ProjectService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Get(ctx context.Context, in *ProjectGetRequest, opts ...grpc.CallOption) (*ProjectResponse, error) {
	out := new(ProjectResponse)
	err := c.cc.Invoke(ctx, "/v1.ProjectService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *projectServiceClient) Find(ctx context.Context, in *ProjectFindRequest, opts ...grpc.CallOption) (*ProjectListResponse, error) {
	out := new(ProjectListResponse)
	err := c.cc.Invoke(ctx, "/v1.ProjectService/Find", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProjectServiceServer is the server API for ProjectService service.
type ProjectServiceServer interface {
	Create(context.Context, *ProjectCreateRequest) (*ProjectResponse, error)
	Update(context.Context, *ProjectUpdateRequest) (*ProjectResponse, error)
	Delete(context.Context, *ProjectDeleteRequest) (*ProjectResponse, error)
	Get(context.Context, *ProjectGetRequest) (*ProjectResponse, error)
	Find(context.Context, *ProjectFindRequest) (*ProjectListResponse, error)
}

// UnimplementedProjectServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProjectServiceServer struct {
}

func (*UnimplementedProjectServiceServer) Create(ctx context.Context, req *ProjectCreateRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (*UnimplementedProjectServiceServer) Update(ctx context.Context, req *ProjectUpdateRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedProjectServiceServer) Delete(ctx context.Context, req *ProjectDeleteRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedProjectServiceServer) Get(ctx context.Context, req *ProjectGetRequest) (*ProjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (*UnimplementedProjectServiceServer) Find(ctx context.Context, req *ProjectFindRequest) (*ProjectListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Find not implemented")
}

func RegisterProjectServiceServer(s *grpc.Server, srv ProjectServiceServer) {
	s.RegisterService(&_ProjectService_serviceDesc, srv)
}

func _ProjectService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProjectService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Create(ctx, req.(*ProjectCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProjectService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Update(ctx, req.(*ProjectUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProjectService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Delete(ctx, req.(*ProjectDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProjectService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Get(ctx, req.(*ProjectGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProjectService_Find_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProjectServiceServer).Find(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ProjectService/Find",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProjectServiceServer).Find(ctx, req.(*ProjectFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ProjectService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ProjectService",
	HandlerType: (*ProjectServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _ProjectService_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _ProjectService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _ProjectService_Delete_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _ProjectService_Get_Handler,
		},
		{
			MethodName: "Find",
			Handler:    _ProjectService_Find_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "v1/project.proto",
}
