// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/v1/project.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Project is the database model
type Project struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TenantId      string                 `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Quotas        *QuotaSet              `protobuf:"bytes,5,opt,name=quotas,proto3" json:"quotas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Project) Reset() {
	*x = Project{}
	mi := &file_api_v1_project_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Project) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Project) ProtoMessage() {}

func (x *Project) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Project.ProtoReflect.Descriptor instead.
func (*Project) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{0}
}

func (x *Project) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Project) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Project) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Project) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Project) GetQuotas() *QuotaSet {
	if x != nil {
		return x.Quotas
	}
	return nil
}

type ProjectCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectCreateRequest) Reset() {
	*x = ProjectCreateRequest{}
	mi := &file_api_v1_project_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectCreateRequest) ProtoMessage() {}

func (x *ProjectCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectCreateRequest.ProtoReflect.Descriptor instead.
func (*ProjectCreateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{1}
}

func (x *ProjectCreateRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type ProjectUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectUpdateRequest) Reset() {
	*x = ProjectUpdateRequest{}
	mi := &file_api_v1_project_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectUpdateRequest) ProtoMessage() {}

func (x *ProjectUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectUpdateRequest.ProtoReflect.Descriptor instead.
func (*ProjectUpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{2}
}

func (x *ProjectUpdateRequest) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type ProjectDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectDeleteRequest) Reset() {
	*x = ProjectDeleteRequest{}
	mi := &file_api_v1_project_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectDeleteRequest) ProtoMessage() {}

func (x *ProjectDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectDeleteRequest.ProtoReflect.Descriptor instead.
func (*ProjectDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{3}
}

func (x *ProjectDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectGetRequest) Reset() {
	*x = ProjectGetRequest{}
	mi := &file_api_v1_project_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectGetRequest) ProtoMessage() {}

func (x *ProjectGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectGetRequest.ProtoReflect.Descriptor instead.
func (*ProjectGetRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{4}
}

func (x *ProjectGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProjectGetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectGetHistoryRequest) Reset() {
	*x = ProjectGetHistoryRequest{}
	mi := &file_api_v1_project_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectGetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectGetHistoryRequest) ProtoMessage() {}

func (x *ProjectGetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectGetHistoryRequest.ProtoReflect.Descriptor instead.
func (*ProjectGetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{5}
}

func (x *ProjectGetHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProjectGetHistoryRequest) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type ProjectFindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	TenantId      *string                `protobuf:"bytes,4,opt,name=tenant_id,json=tenantId,proto3,oneof" json:"tenant_id,omitempty"`
	Paging        *Paging                `protobuf:"bytes,5,opt,name=paging,proto3" json:"paging,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectFindRequest) Reset() {
	*x = ProjectFindRequest{}
	mi := &file_api_v1_project_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectFindRequest) ProtoMessage() {}

func (x *ProjectFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectFindRequest.ProtoReflect.Descriptor instead.
func (*ProjectFindRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectFindRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *ProjectFindRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *ProjectFindRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *ProjectFindRequest) GetTenantId() string {
	if x != nil && x.TenantId != nil {
		return *x.TenantId
	}
	return ""
}

func (x *ProjectFindRequest) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *ProjectFindRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

type ProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectResponse) Reset() {
	*x = ProjectResponse{}
	mi := &file_api_v1_project_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectResponse) ProtoMessage() {}

func (x *ProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectResponse.ProtoReflect.Descriptor instead.
func (*ProjectResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{7}
}

func (x *ProjectResponse) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

type ProjectListResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Projects []*Project             `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	// next_page_token is used for pagination, returns the next page to be fetched and must then be provided in the list request.
	NextPage      *uint64 `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProjectListResponse) Reset() {
	*x = ProjectListResponse{}
	mi := &file_api_v1_project_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectListResponse) ProtoMessage() {}

func (x *ProjectListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_project_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectListResponse.ProtoReflect.Descriptor instead.
func (*ProjectListResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_project_proto_rawDescGZIP(), []int{8}
}

func (x *ProjectListResponse) GetProjects() []*Project {
	if x != nil {
		return x.Projects
	}
	return nil
}

func (x *ProjectListResponse) GetNextPage() uint64 {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return 0
}

var File_api_v1_project_proto protoreflect.FileDescriptor

const file_api_v1_project_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/project.proto\x12\x06api.v1\x1a\x13api/v1/common.proto\x1a\x11api/v1/meta.proto\x1a\x12api/v1/quota.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x01\n" +
	"\aProject\x12 \n" +
	"\x04meta\x18\x01 \x01(\v2\f.api.v1.MetaR\x04meta\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1b\n" +
	"\ttenant_id\x18\x04 \x01(\tR\btenantId\x12(\n" +
	"\x06quotas\x18\x05 \x01(\v2\x10.api.v1.QuotaSetR\x06quotas\"A\n" +
	"\x14ProjectCreateRequest\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"A\n" +
	"\x14ProjectUpdateRequest\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"&\n" +
	"\x14ProjectDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"#\n" +
	"\x11ProjectGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"V\n" +
	"\x18ProjectGetHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\xf0\x02\n" +
	"\x12ProjectFindRequest\x12\x13\n" +
	"\x02id\x18\x01 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x02R\vdescription\x88\x01\x01\x12 \n" +
	"\ttenant_id\x18\x04 \x01(\tH\x03R\btenantId\x88\x01\x01\x12&\n" +
	"\x06paging\x18\x05 \x01(\v2\x0e.api.v1.PagingR\x06paging\x12M\n" +
	"\vannotations\x18\x06 \x03(\v2+.api.v1.ProjectFindRequest.AnnotationsEntryR\vannotations\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\f\n" +
	"\n" +
	"_tenant_id\"<\n" +
	"\x0fProjectResponse\x12)\n" +
	"\aproject\x18\x01 \x01(\v2\x0f.api.v1.ProjectR\aproject\"r\n" +
	"\x13ProjectListResponse\x12+\n" +
	"\bprojects\x18\x01 \x03(\v2\x0f.api.v1.ProjectR\bprojects\x12 \n" +
	"\tnext_page\x18\x02 \x01(\x04H\x00R\bnextPage\x88\x01\x01B\f\n" +
	"\n" +
	"_next_page2\x98\x03\n" +
	"\x0eProjectService\x12?\n" +
	"\x06Create\x12\x1c.api.v1.ProjectCreateRequest\x1a\x17.api.v1.ProjectResponse\x12?\n" +
	"\x06Update\x12\x1c.api.v1.ProjectUpdateRequest\x1a\x17.api.v1.ProjectResponse\x12?\n" +
	"\x06Delete\x12\x1c.api.v1.ProjectDeleteRequest\x1a\x17.api.v1.ProjectResponse\x129\n" +
	"\x03Get\x12\x19.api.v1.ProjectGetRequest\x1a\x17.api.v1.ProjectResponse\x12G\n" +
	"\n" +
	"GetHistory\x12 .api.v1.ProjectGetHistoryRequest\x1a\x17.api.v1.ProjectResponse\x12?\n" +
	"\x04Find\x12\x1a.api.v1.ProjectFindRequest\x1a\x1b.api.v1.ProjectListResponseB\x87\x01\n" +
	"\n" +
	"com.api.v1B\fProjectProtoP\x01Z2github.com/metal-stack/masterdata-api/api/v1;apiv1\xa2\x02\x03AXX\xaa\x02\x06Api.V1\xca\x02\x06Api\\V1\xe2\x02\x12Api\\V1\\GPBMetadata\xea\x02\aApi::V1b\x06proto3"

var (
	file_api_v1_project_proto_rawDescOnce sync.Once
	file_api_v1_project_proto_rawDescData []byte
)

func file_api_v1_project_proto_rawDescGZIP() []byte {
	file_api_v1_project_proto_rawDescOnce.Do(func() {
		file_api_v1_project_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_project_proto_rawDesc), len(file_api_v1_project_proto_rawDesc)))
	})
	return file_api_v1_project_proto_rawDescData
}

var file_api_v1_project_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_api_v1_project_proto_goTypes = []any{
	(*Project)(nil),                  // 0: api.v1.Project
	(*ProjectCreateRequest)(nil),     // 1: api.v1.ProjectCreateRequest
	(*ProjectUpdateRequest)(nil),     // 2: api.v1.ProjectUpdateRequest
	(*ProjectDeleteRequest)(nil),     // 3: api.v1.ProjectDeleteRequest
	(*ProjectGetRequest)(nil),        // 4: api.v1.ProjectGetRequest
	(*ProjectGetHistoryRequest)(nil), // 5: api.v1.ProjectGetHistoryRequest
	(*ProjectFindRequest)(nil),       // 6: api.v1.ProjectFindRequest
	(*ProjectResponse)(nil),          // 7: api.v1.ProjectResponse
	(*ProjectListResponse)(nil),      // 8: api.v1.ProjectListResponse
	nil,                              // 9: api.v1.ProjectFindRequest.AnnotationsEntry
	(*Meta)(nil),                     // 10: api.v1.Meta
	(*QuotaSet)(nil),                 // 11: api.v1.QuotaSet
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
	(*Paging)(nil),                   // 13: api.v1.Paging
}
var file_api_v1_project_proto_depIdxs = []int32{
	10, // 0: api.v1.Project.meta:type_name -> api.v1.Meta
	11, // 1: api.v1.Project.quotas:type_name -> api.v1.QuotaSet
	0,  // 2: api.v1.ProjectCreateRequest.project:type_name -> api.v1.Project
	0,  // 3: api.v1.ProjectUpdateRequest.project:type_name -> api.v1.Project
	12, // 4: api.v1.ProjectGetHistoryRequest.at:type_name -> google.protobuf.Timestamp
	13, // 5: api.v1.ProjectFindRequest.paging:type_name -> api.v1.Paging
	9,  // 6: api.v1.ProjectFindRequest.annotations:type_name -> api.v1.ProjectFindRequest.AnnotationsEntry
	0,  // 7: api.v1.ProjectResponse.project:type_name -> api.v1.Project
	0,  // 8: api.v1.ProjectListResponse.projects:type_name -> api.v1.Project
	1,  // 9: api.v1.ProjectService.Create:input_type -> api.v1.ProjectCreateRequest
	2,  // 10: api.v1.ProjectService.Update:input_type -> api.v1.ProjectUpdateRequest
	3,  // 11: api.v1.ProjectService.Delete:input_type -> api.v1.ProjectDeleteRequest
	4,  // 12: api.v1.ProjectService.Get:input_type -> api.v1.ProjectGetRequest
	5,  // 13: api.v1.ProjectService.GetHistory:input_type -> api.v1.ProjectGetHistoryRequest
	6,  // 14: api.v1.ProjectService.Find:input_type -> api.v1.ProjectFindRequest
	7,  // 15: api.v1.ProjectService.Create:output_type -> api.v1.ProjectResponse
	7,  // 16: api.v1.ProjectService.Update:output_type -> api.v1.ProjectResponse
	7,  // 17: api.v1.ProjectService.Delete:output_type -> api.v1.ProjectResponse
	7,  // 18: api.v1.ProjectService.Get:output_type -> api.v1.ProjectResponse
	7,  // 19: api.v1.ProjectService.GetHistory:output_type -> api.v1.ProjectResponse
	8,  // 20: api.v1.ProjectService.Find:output_type -> api.v1.ProjectListResponse
	15, // [15:21] is the sub-list for method output_type
	9,  // [9:15] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_v1_project_proto_init() }
func file_api_v1_project_proto_init() {
	if File_api_v1_project_proto != nil {
		return
	}
	file_api_v1_common_proto_init()
	file_api_v1_meta_proto_init()
	file_api_v1_quota_proto_init()
	file_api_v1_project_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_v1_project_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_project_proto_rawDesc), len(file_api_v1_project_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_project_proto_goTypes,
		DependencyIndexes: file_api_v1_project_proto_depIdxs,
		MessageInfos:      file_api_v1_project_proto_msgTypes,
	}.Build()
	File_api_v1_project_proto = out.File
	file_api_v1_project_proto_goTypes = nil
	file_api_v1_project_proto_depIdxs = nil
}
