// Code generated by protoc-gen-go. DO NOT EDIT.
// source: v1/quota.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// QuotaSet defines the types of possible Quotas
// might be specified by project or tenant
// whatever quota is reached first counts
// it always defines the max amount of this type
type QuotaSet struct {
	// cluster the amount of clusters
	Cluster *Quota `protobuf:"bytes,1,opt,name=cluster,proto3" json:"cluster,omitempty"`
	// machine the amount of machines
	Machine *Quota `protobuf:"bytes,2,opt,name=machine,proto3" json:"machine,omitempty"`
	// ip the amount of aquired ip´s
	Ip *Quota `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// project the amount of projects of a tenant
	Project              *Quota   `protobuf:"bytes,4,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *QuotaSet) Reset()         { *m = QuotaSet{} }
func (m *QuotaSet) String() string { return proto.CompactTextString(m) }
func (*QuotaSet) ProtoMessage()    {}
func (*QuotaSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa4cec8749083f6, []int{0}
}

func (m *QuotaSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_QuotaSet.Unmarshal(m, b)
}
func (m *QuotaSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_QuotaSet.Marshal(b, m, deterministic)
}
func (m *QuotaSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QuotaSet.Merge(m, src)
}
func (m *QuotaSet) XXX_Size() int {
	return xxx_messageInfo_QuotaSet.Size(m)
}
func (m *QuotaSet) XXX_DiscardUnknown() {
	xxx_messageInfo_QuotaSet.DiscardUnknown(m)
}

var xxx_messageInfo_QuotaSet proto.InternalMessageInfo

func (m *QuotaSet) GetCluster() *Quota {
	if m != nil {
		return m.Cluster
	}
	return nil
}

func (m *QuotaSet) GetMachine() *Quota {
	if m != nil {
		return m.Machine
	}
	return nil
}

func (m *QuotaSet) GetIp() *Quota {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *QuotaSet) GetProject() *Quota {
	if m != nil {
		return m.Project
	}
	return nil
}

// Quota is the actual maximum amount
type Quota struct {
	// quota is the maximum amount for the current QuotaSet, can be nil
	Quota                *wrappers.Int32Value `protobuf:"bytes,1,opt,name=quota,proto3" json:"quota,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Quota) Reset()         { *m = Quota{} }
func (m *Quota) String() string { return proto.CompactTextString(m) }
func (*Quota) ProtoMessage()    {}
func (*Quota) Descriptor() ([]byte, []int) {
	return fileDescriptor_6fa4cec8749083f6, []int{1}
}

func (m *Quota) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Quota.Unmarshal(m, b)
}
func (m *Quota) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Quota.Marshal(b, m, deterministic)
}
func (m *Quota) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Quota.Merge(m, src)
}
func (m *Quota) XXX_Size() int {
	return xxx_messageInfo_Quota.Size(m)
}
func (m *Quota) XXX_DiscardUnknown() {
	xxx_messageInfo_Quota.DiscardUnknown(m)
}

var xxx_messageInfo_Quota proto.InternalMessageInfo

func (m *Quota) GetQuota() *wrappers.Int32Value {
	if m != nil {
		return m.Quota
	}
	return nil
}

func init() {
	proto.RegisterType((*QuotaSet)(nil), "v1.QuotaSet")
	proto.RegisterType((*Quota)(nil), "v1.Quota")
}

func init() {
	proto.RegisterFile("v1/quota.proto", fileDescriptor_6fa4cec8749083f6)
}

var fileDescriptor_6fa4cec8749083f6 = []byte{
	// 192 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x33, 0xd4, 0x2f,
	0x2c, 0xcd, 0x2f, 0x49, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x33, 0x94, 0x92,
	0x4b, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5, 0x07, 0x8b, 0x24, 0x95, 0xa6, 0xe9, 0x97, 0x17, 0x25,
	0x16, 0x14, 0xa4, 0x16, 0x15, 0x43, 0xd4, 0x28, 0x4d, 0x61, 0xe4, 0xe2, 0x08, 0x04, 0xe9, 0x09,
	0x4e, 0x2d, 0x11, 0x52, 0xe6, 0x62, 0x4f, 0xce, 0x29, 0x2d, 0x2e, 0x49, 0x2d, 0x92, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x36, 0xe2, 0xd4, 0x2b, 0x33, 0xd4, 0x03, 0x4b, 0x07, 0xc1, 0x64, 0x40, 0x8a,
	0x72, 0x13, 0x93, 0x33, 0x32, 0xf3, 0x52, 0x25, 0x98, 0x30, 0x14, 0x41, 0x65, 0x84, 0x24, 0xb9,
	0x98, 0x32, 0x0b, 0x24, 0x98, 0xd1, 0xe5, 0x99, 0x32, 0x0b, 0x40, 0xfa, 0x0b, 0x8a, 0xf2, 0xb3,
	0x52, 0x93, 0x4b, 0x24, 0x58, 0x30, 0xf4, 0x43, 0x65, 0x94, 0xac, 0xb8, 0x58, 0xc1, 0x22, 0x42,
	0x86, 0x5c, 0xac, 0x60, 0x2f, 0x41, 0x1d, 0x24, 0xad, 0x07, 0xf1, 0x8f, 0x1e, 0xcc, 0x3f, 0x7a,
	0x9e, 0x79, 0x25, 0xc6, 0x46, 0x61, 0x89, 0x39, 0xa5, 0xa9, 0x41, 0x10, 0x95, 0x49, 0x6c, 0x60,
	0x39, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x1f, 0xd4, 0x15, 0x0f, 0x01, 0x00, 0x00,
}
