// This file was automatically generated by pkg/gen/genscanvaluer.
// DO NOT EDIT MANUALLY.
// Regenerate with "go generate" or "make generate"

package v1

import (
	"database/sql/driver"
	"fmt"
)

func (m Tenant) Schema() string {
	return `
	CREATE TABLE IF NOT EXISTS tenants (
		id   text PRIMARY KEY NOT NULL,
		tenant JSONB NOT NULL
	);
	CREATE INDEX IF NOT EXISTS tenant_idx ON tenants USING GIN(tenant);

	CREATE TABLE IF NOT EXISTS tenants_history (
		id         text NOT NULL,
		op         char NOT NULL,
		created_at timestamptz NOT NULL,
		tenant JSONB NOT NULL
	);
	CREATE INDEX IF NOT EXISTS tenants_history_id_created_at_idx ON tenants_history USING btree(id, created_at);
`
}

func (m Tenant) JSONField() string {
	return "tenant"
}

func (m Tenant) TableName() string {
	return "tenants"
}

func (m Tenant) Kind() string {
	return "Tenant"
}

func (m Tenant) APIVersion() string {
	return "v1"
}

// Value make the Tenant struct implement the driver.Valuer interface. This method
// simply returns the JSON-encoded representation of the struct.
func (m Tenant) Value() (driver.Value, error) {
	return json.Marshal(m)
}

// Scan make the Tenant struct implement the sql.Scanner interface. This method
// simply decodes a JSON-encoded value into the struct fields.
func (m *Tenant) Scan(value interface{}) error {
	b, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("type assertion to []byte failed")
	}

	err := json.Unmarshal(b, m)
	return err
}
