// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: v1/tenant.proto

package v1

import (
	_type "github.com/metal-stack/masterdata-api/google/type"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FindParticipatingProjectsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IncludeInherited *bool                  `protobuf:"varint,2,opt,name=include_inherited,json=includeInherited,proto3,oneof" json:"include_inherited,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindParticipatingProjectsRequest) Reset() {
	*x = FindParticipatingProjectsRequest{}
	mi := &file_v1_tenant_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindParticipatingProjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindParticipatingProjectsRequest) ProtoMessage() {}

func (x *FindParticipatingProjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindParticipatingProjectsRequest.ProtoReflect.Descriptor instead.
func (*FindParticipatingProjectsRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{0}
}

func (x *FindParticipatingProjectsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FindParticipatingProjectsRequest) GetIncludeInherited() bool {
	if x != nil && x.IncludeInherited != nil {
		return *x.IncludeInherited
	}
	return false
}

type FindParticipatingTenantsRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IncludeInherited *bool                  `protobuf:"varint,2,opt,name=include_inherited,json=includeInherited,proto3,oneof" json:"include_inherited,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FindParticipatingTenantsRequest) Reset() {
	*x = FindParticipatingTenantsRequest{}
	mi := &file_v1_tenant_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindParticipatingTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindParticipatingTenantsRequest) ProtoMessage() {}

func (x *FindParticipatingTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindParticipatingTenantsRequest.ProtoReflect.Descriptor instead.
func (*FindParticipatingTenantsRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{1}
}

func (x *FindParticipatingTenantsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *FindParticipatingTenantsRequest) GetIncludeInherited() bool {
	if x != nil && x.IncludeInherited != nil {
		return *x.IncludeInherited
	}
	return false
}

type ListTenantMembersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TenantId         string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IncludeInherited *bool                  `protobuf:"varint,2,opt,name=include_inherited,json=includeInherited,proto3,oneof" json:"include_inherited,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListTenantMembersRequest) Reset() {
	*x = ListTenantMembersRequest{}
	mi := &file_v1_tenant_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantMembersRequest) ProtoMessage() {}

func (x *ListTenantMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantMembersRequest.ProtoReflect.Descriptor instead.
func (*ListTenantMembersRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{2}
}

func (x *ListTenantMembersRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListTenantMembersRequest) GetIncludeInherited() bool {
	if x != nil && x.IncludeInherited != nil {
		return *x.IncludeInherited
	}
	return false
}

type ListTenantMembersResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Tenants       []*TenantWithMembershipAnnotations `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantMembersResponse) Reset() {
	*x = ListTenantMembersResponse{}
	mi := &file_v1_tenant_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantMembersResponse) ProtoMessage() {}

func (x *ListTenantMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantMembersResponse.ProtoReflect.Descriptor instead.
func (*ListTenantMembersResponse) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{3}
}

func (x *ListTenantMembersResponse) GetTenants() []*TenantWithMembershipAnnotations {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type FindParticipatingProjectsResponse struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	Projects      []*ProjectWithMembershipAnnotations `protobuf:"bytes,1,rep,name=projects,proto3" json:"projects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindParticipatingProjectsResponse) Reset() {
	*x = FindParticipatingProjectsResponse{}
	mi := &file_v1_tenant_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindParticipatingProjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindParticipatingProjectsResponse) ProtoMessage() {}

func (x *FindParticipatingProjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindParticipatingProjectsResponse.ProtoReflect.Descriptor instead.
func (*FindParticipatingProjectsResponse) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{4}
}

func (x *FindParticipatingProjectsResponse) GetProjects() []*ProjectWithMembershipAnnotations {
	if x != nil {
		return x.Projects
	}
	return nil
}

type FindParticipatingTenantsResponse struct {
	state         protoimpl.MessageState             `protogen:"open.v1"`
	Tenants       []*TenantWithMembershipAnnotations `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindParticipatingTenantsResponse) Reset() {
	*x = FindParticipatingTenantsResponse{}
	mi := &file_v1_tenant_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindParticipatingTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindParticipatingTenantsResponse) ProtoMessage() {}

func (x *FindParticipatingTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindParticipatingTenantsResponse.ProtoReflect.Descriptor instead.
func (*FindParticipatingTenantsResponse) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{5}
}

func (x *FindParticipatingTenantsResponse) GetTenants() []*TenantWithMembershipAnnotations {
	if x != nil {
		return x.Tenants
	}
	return nil
}

type ProjectWithMembershipAnnotations struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Project            *Project               `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	ProjectAnnotations map[string]string      `protobuf:"bytes,2,rep,name=project_annotations,json=projectAnnotations,proto3" json:"project_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantAnnotations  map[string]string      `protobuf:"bytes,3,rep,name=tenant_annotations,json=tenantAnnotations,proto3" json:"tenant_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProjectWithMembershipAnnotations) Reset() {
	*x = ProjectWithMembershipAnnotations{}
	mi := &file_v1_tenant_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProjectWithMembershipAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProjectWithMembershipAnnotations) ProtoMessage() {}

func (x *ProjectWithMembershipAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProjectWithMembershipAnnotations.ProtoReflect.Descriptor instead.
func (*ProjectWithMembershipAnnotations) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{6}
}

func (x *ProjectWithMembershipAnnotations) GetProject() *Project {
	if x != nil {
		return x.Project
	}
	return nil
}

func (x *ProjectWithMembershipAnnotations) GetProjectAnnotations() map[string]string {
	if x != nil {
		return x.ProjectAnnotations
	}
	return nil
}

func (x *ProjectWithMembershipAnnotations) GetTenantAnnotations() map[string]string {
	if x != nil {
		return x.TenantAnnotations
	}
	return nil
}

type TenantWithMembershipAnnotations struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Tenant             *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	ProjectAnnotations map[string]string      `protobuf:"bytes,2,rep,name=project_annotations,json=projectAnnotations,proto3" json:"project_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TenantAnnotations  map[string]string      `protobuf:"bytes,3,rep,name=tenant_annotations,json=tenantAnnotations,proto3" json:"tenant_annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ProjectIDs contains all project IDs of this tenant for which an explicit project membership exists
	ProjectIds    []string `protobuf:"bytes,4,rep,name=project_ids,json=projectIds,proto3" json:"project_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantWithMembershipAnnotations) Reset() {
	*x = TenantWithMembershipAnnotations{}
	mi := &file_v1_tenant_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantWithMembershipAnnotations) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantWithMembershipAnnotations) ProtoMessage() {}

func (x *TenantWithMembershipAnnotations) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantWithMembershipAnnotations.ProtoReflect.Descriptor instead.
func (*TenantWithMembershipAnnotations) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{7}
}

func (x *TenantWithMembershipAnnotations) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

func (x *TenantWithMembershipAnnotations) GetProjectAnnotations() map[string]string {
	if x != nil {
		return x.ProjectAnnotations
	}
	return nil
}

func (x *TenantWithMembershipAnnotations) GetTenantAnnotations() map[string]string {
	if x != nil {
		return x.TenantAnnotations
	}
	return nil
}

func (x *TenantWithMembershipAnnotations) GetProjectIds() []string {
	if x != nil {
		return x.ProjectIds
	}
	return nil
}

type Tenant struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Meta           *Meta                  `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DefaultQuotas  *QuotaSet              `protobuf:"bytes,4,opt,name=default_quotas,json=defaultQuotas,proto3" json:"default_quotas,omitempty"`
	Quotas         *QuotaSet              `protobuf:"bytes,5,opt,name=quotas,proto3" json:"quotas,omitempty"`
	IamConfig      *IAMConfig             `protobuf:"bytes,6,opt,name=iam_config,json=iamConfig,proto3" json:"iam_config,omitempty"`
	Payment        *PaymentDetails        `protobuf:"bytes,7,opt,name=payment,proto3" json:"payment,omitempty"`
	ContactDetails *ContactDetails        `protobuf:"bytes,8,opt,name=contact_details,json=contactDetails,proto3" json:"contact_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_v1_tenant_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{8}
}

func (x *Tenant) GetMeta() *Meta {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tenant) GetDefaultQuotas() *QuotaSet {
	if x != nil {
		return x.DefaultQuotas
	}
	return nil
}

func (x *Tenant) GetQuotas() *QuotaSet {
	if x != nil {
		return x.Quotas
	}
	return nil
}

func (x *Tenant) GetIamConfig() *IAMConfig {
	if x != nil {
		return x.IamConfig
	}
	return nil
}

func (x *Tenant) GetPayment() *PaymentDetails {
	if x != nil {
		return x.Payment
	}
	return nil
}

func (x *Tenant) GetContactDetails() *ContactDetails {
	if x != nil {
		return x.ContactDetails
	}
	return nil
}

type TenantCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantCreateRequest) Reset() {
	*x = TenantCreateRequest{}
	mi := &file_v1_tenant_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantCreateRequest) ProtoMessage() {}

func (x *TenantCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantCreateRequest.ProtoReflect.Descriptor instead.
func (*TenantCreateRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{9}
}

func (x *TenantCreateRequest) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type TenantUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantUpdateRequest) Reset() {
	*x = TenantUpdateRequest{}
	mi := &file_v1_tenant_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantUpdateRequest) ProtoMessage() {}

func (x *TenantUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantUpdateRequest.ProtoReflect.Descriptor instead.
func (*TenantUpdateRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{10}
}

func (x *TenantUpdateRequest) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type TenantDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantDeleteRequest) Reset() {
	*x = TenantDeleteRequest{}
	mi := &file_v1_tenant_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantDeleteRequest) ProtoMessage() {}

func (x *TenantDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantDeleteRequest.ProtoReflect.Descriptor instead.
func (*TenantDeleteRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{11}
}

func (x *TenantDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TenantGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantGetRequest) Reset() {
	*x = TenantGetRequest{}
	mi := &file_v1_tenant_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantGetRequest) ProtoMessage() {}

func (x *TenantGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantGetRequest.ProtoReflect.Descriptor instead.
func (*TenantGetRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{12}
}

func (x *TenantGetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TenantGetHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	At            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=at,proto3" json:"at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantGetHistoryRequest) Reset() {
	*x = TenantGetHistoryRequest{}
	mi := &file_v1_tenant_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantGetHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantGetHistoryRequest) ProtoMessage() {}

func (x *TenantGetHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantGetHistoryRequest.ProtoReflect.Descriptor instead.
func (*TenantGetHistoryRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{13}
}

func (x *TenantGetHistoryRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TenantGetHistoryRequest) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

type TenantFindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paging        *Paging                `protobuf:"bytes,3,opt,name=paging,proto3" json:"paging,omitempty"`
	Annotations   map[string]string      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Id            *string                `protobuf:"bytes,5,opt,name=id,proto3,oneof" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name,proto3,oneof" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantFindRequest) Reset() {
	*x = TenantFindRequest{}
	mi := &file_v1_tenant_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantFindRequest) ProtoMessage() {}

func (x *TenantFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantFindRequest.ProtoReflect.Descriptor instead.
func (*TenantFindRequest) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{14}
}

func (x *TenantFindRequest) GetPaging() *Paging {
	if x != nil {
		return x.Paging
	}
	return nil
}

func (x *TenantFindRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *TenantFindRequest) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *TenantFindRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type TenantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenant        *Tenant                `protobuf:"bytes,1,opt,name=tenant,proto3" json:"tenant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantResponse) Reset() {
	*x = TenantResponse{}
	mi := &file_v1_tenant_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantResponse) ProtoMessage() {}

func (x *TenantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantResponse.ProtoReflect.Descriptor instead.
func (*TenantResponse) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{15}
}

func (x *TenantResponse) GetTenant() *Tenant {
	if x != nil {
		return x.Tenant
	}
	return nil
}

type TenantListResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Tenants []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	// next_page is used for pagination, returns the next page to be fetched and must then be provided in the list request.
	NextPage      *uint64 `protobuf:"varint,2,opt,name=next_page,json=nextPage,proto3,oneof" json:"next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TenantListResponse) Reset() {
	*x = TenantListResponse{}
	mi := &file_v1_tenant_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TenantListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TenantListResponse) ProtoMessage() {}

func (x *TenantListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TenantListResponse.ProtoReflect.Descriptor instead.
func (*TenantListResponse) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{16}
}

func (x *TenantListResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

func (x *TenantListResponse) GetNextPage() uint64 {
	if x != nil && x.NextPage != nil {
		return *x.NextPage
	}
	return 0
}

// PaymentDetails describe payment specific configurations of a tenant
type PaymentDetails struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Details stored as key value pairs
	Details map[string]string `protobuf:"bytes,1,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Annotations of this payment details
	Annotations map[string]string `protobuf:"bytes,2,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Labels of this payment details
	Labels        []string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentDetails) Reset() {
	*x = PaymentDetails{}
	mi := &file_v1_tenant_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentDetails) ProtoMessage() {}

func (x *PaymentDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentDetails.ProtoReflect.Descriptor instead.
func (*PaymentDetails) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{17}
}

func (x *PaymentDetails) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *PaymentDetails) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *PaymentDetails) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ContactDetails contain more properties of a tenant
type ContactDetails struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Email       string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Address     *_type.PostalAddress   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	AvatarUrl   string                 `protobuf:"bytes,4,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	// Annotations of this payment details
	Annotations map[string]string `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Labels of this payment details
	Labels        []string `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContactDetails) Reset() {
	*x = ContactDetails{}
	mi := &file_v1_tenant_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContactDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContactDetails) ProtoMessage() {}

func (x *ContactDetails) ProtoReflect() protoreflect.Message {
	mi := &file_v1_tenant_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContactDetails.ProtoReflect.Descriptor instead.
func (*ContactDetails) Descriptor() ([]byte, []int) {
	return file_v1_tenant_proto_rawDescGZIP(), []int{18}
}

func (x *ContactDetails) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ContactDetails) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *ContactDetails) GetAddress() *_type.PostalAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ContactDetails) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *ContactDetails) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ContactDetails) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_v1_tenant_proto protoreflect.FileDescriptor

const file_v1_tenant_proto_rawDesc = "" +
	"\n" +
	"\x0fv1/tenant.proto\x12\x02v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/type/postal_address.proto\x1a\x0fv1/common.proto\x1a\fv1/iam.proto\x1a\rv1/meta.proto\x1a\x10v1/project.proto\x1a\x0ev1/quota.proto\"\x87\x01\n" +
	" FindParticipatingProjectsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x120\n" +
	"\x11include_inherited\x18\x02 \x01(\bH\x00R\x10includeInherited\x88\x01\x01B\x14\n" +
	"\x12_include_inherited\"\x86\x01\n" +
	"\x1fFindParticipatingTenantsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x120\n" +
	"\x11include_inherited\x18\x02 \x01(\bH\x00R\x10includeInherited\x88\x01\x01B\x14\n" +
	"\x12_include_inherited\"\x7f\n" +
	"\x18ListTenantMembersRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x120\n" +
	"\x11include_inherited\x18\x02 \x01(\bH\x00R\x10includeInherited\x88\x01\x01B\x14\n" +
	"\x12_include_inherited\"Z\n" +
	"\x19ListTenantMembersResponse\x12=\n" +
	"\atenants\x18\x01 \x03(\v2#.v1.TenantWithMembershipAnnotationsR\atenants\"e\n" +
	"!FindParticipatingProjectsResponse\x12@\n" +
	"\bprojects\x18\x01 \x03(\v2$.v1.ProjectWithMembershipAnnotationsR\bprojects\"a\n" +
	" FindParticipatingTenantsResponse\x12=\n" +
	"\atenants\x18\x01 \x03(\v2#.v1.TenantWithMembershipAnnotationsR\atenants\"\xb1\x03\n" +
	" ProjectWithMembershipAnnotations\x12%\n" +
	"\aproject\x18\x01 \x01(\v2\v.v1.ProjectR\aproject\x12m\n" +
	"\x13project_annotations\x18\x02 \x03(\v2<.v1.ProjectWithMembershipAnnotations.ProjectAnnotationsEntryR\x12projectAnnotations\x12j\n" +
	"\x12tenant_annotations\x18\x03 \x03(\v2;.v1.ProjectWithMembershipAnnotations.TenantAnnotationsEntryR\x11tenantAnnotations\x1aE\n" +
	"\x17ProjectAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16TenantAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcc\x03\n" +
	"\x1fTenantWithMembershipAnnotations\x12\"\n" +
	"\x06tenant\x18\x01 \x01(\v2\n" +
	".v1.TenantR\x06tenant\x12l\n" +
	"\x13project_annotations\x18\x02 \x03(\v2;.v1.TenantWithMembershipAnnotations.ProjectAnnotationsEntryR\x12projectAnnotations\x12i\n" +
	"\x12tenant_annotations\x18\x03 \x03(\v2:.v1.TenantWithMembershipAnnotations.TenantAnnotationsEntryR\x11tenantAnnotations\x12\x1f\n" +
	"\vproject_ids\x18\x04 \x03(\tR\n" +
	"projectIds\x1aE\n" +
	"\x17ProjectAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16TenantAnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x02\n" +
	"\x06Tenant\x12\x1c\n" +
	"\x04meta\x18\x01 \x01(\v2\b.v1.MetaR\x04meta\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x123\n" +
	"\x0edefault_quotas\x18\x04 \x01(\v2\f.v1.QuotaSetR\rdefaultQuotas\x12$\n" +
	"\x06quotas\x18\x05 \x01(\v2\f.v1.QuotaSetR\x06quotas\x12,\n" +
	"\n" +
	"iam_config\x18\x06 \x01(\v2\r.v1.IAMConfigR\tiamConfig\x12,\n" +
	"\apayment\x18\a \x01(\v2\x12.v1.PaymentDetailsR\apayment\x12;\n" +
	"\x0fcontact_details\x18\b \x01(\v2\x12.v1.ContactDetailsR\x0econtactDetails\"9\n" +
	"\x13TenantCreateRequest\x12\"\n" +
	"\x06tenant\x18\x01 \x01(\v2\n" +
	".v1.TenantR\x06tenant\"9\n" +
	"\x13TenantUpdateRequest\x12\"\n" +
	"\x06tenant\x18\x01 \x01(\v2\n" +
	".v1.TenantR\x06tenant\"%\n" +
	"\x13TenantDeleteRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\"\n" +
	"\x10TenantGetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x17TenantGetHistoryRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x02at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\"\xab\x02\n" +
	"\x11TenantFindRequest\x12\"\n" +
	"\x06paging\x18\x03 \x01(\v2\n" +
	".v1.PagingR\x06paging\x12H\n" +
	"\vannotations\x18\x04 \x03(\v2&.v1.TenantFindRequest.AnnotationsEntryR\vannotations\x12\x13\n" +
	"\x02id\x18\x05 \x01(\tH\x00R\x02id\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x06 \x01(\tH\x01R\x04name\x88\x01\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_idB\a\n" +
	"\x05_nameJ\x04\b\x01\x10\x02J\x04\b\x02\x10\x03R\rdeprecated_idR\x0fdeprecated_name\"4\n" +
	"\x0eTenantResponse\x12\"\n" +
	"\x06tenant\x18\x01 \x01(\v2\n" +
	".v1.TenantR\x06tenant\"j\n" +
	"\x12TenantListResponse\x12$\n" +
	"\atenants\x18\x01 \x03(\v2\n" +
	".v1.TenantR\atenants\x12 \n" +
	"\tnext_page\x18\x02 \x01(\x04H\x00R\bnextPage\x88\x01\x01B\f\n" +
	"\n" +
	"_next_page\"\xa6\x02\n" +
	"\x0ePaymentDetails\x129\n" +
	"\adetails\x18\x01 \x03(\v2\x1f.v1.PaymentDetails.DetailsEntryR\adetails\x12E\n" +
	"\vannotations\x18\x02 \x03(\v2#.v1.PaymentDetails.AnnotationsEntryR\vannotations\x12\x16\n" +
	"\x06labels\x18\x03 \x03(\tR\x06labels\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbd\x02\n" +
	"\x0eContactDetails\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x124\n" +
	"\aaddress\x18\x03 \x01(\v2\x1a.google.type.PostalAddressR\aaddress\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x04 \x01(\tR\tavatarUrl\x12E\n" +
	"\vannotations\x18\x05 \x03(\v2#.v1.ContactDetails.AnnotationsEntryR\vannotations\x12\x16\n" +
	"\x06labels\x18\x06 \x03(\tR\x06labels\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xfe\x04\n" +
	"\rTenantService\x125\n" +
	"\x06Create\x12\x17.v1.TenantCreateRequest\x1a\x12.v1.TenantResponse\x125\n" +
	"\x06Update\x12\x17.v1.TenantUpdateRequest\x1a\x12.v1.TenantResponse\x125\n" +
	"\x06Delete\x12\x17.v1.TenantDeleteRequest\x1a\x12.v1.TenantResponse\x12/\n" +
	"\x03Get\x12\x14.v1.TenantGetRequest\x1a\x12.v1.TenantResponse\x12=\n" +
	"\n" +
	"GetHistory\x12\x1b.v1.TenantGetHistoryRequest\x1a\x12.v1.TenantResponse\x125\n" +
	"\x04Find\x12\x15.v1.TenantFindRequest\x1a\x16.v1.TenantListResponse\x12P\n" +
	"\x11ListTenantMembers\x12\x1c.v1.ListTenantMembersRequest\x1a\x1d.v1.ListTenantMembersResponse\x12h\n" +
	"\x19FindParticipatingProjects\x12$.v1.FindParticipatingProjectsRequest\x1a%.v1.FindParticipatingProjectsResponse\x12e\n" +
	"\x18FindParticipatingTenants\x12#.v1.FindParticipatingTenantsRequest\x1a$.v1.FindParticipatingTenantsResponseBg\n" +
	"\x06com.v1B\vTenantProtoP\x01Z(github.com/metal-stack/masterdata-api/v1\xa2\x02\x03VXX\xaa\x02\x02V1\xca\x02\x02V1\xe2\x02\x0eV1\\GPBMetadata\xea\x02\x02V1b\x06proto3"

var (
	file_v1_tenant_proto_rawDescOnce sync.Once
	file_v1_tenant_proto_rawDescData []byte
)

func file_v1_tenant_proto_rawDescGZIP() []byte {
	file_v1_tenant_proto_rawDescOnce.Do(func() {
		file_v1_tenant_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_tenant_proto_rawDesc), len(file_v1_tenant_proto_rawDesc)))
	})
	return file_v1_tenant_proto_rawDescData
}

var file_v1_tenant_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_v1_tenant_proto_goTypes = []any{
	(*FindParticipatingProjectsRequest)(nil),  // 0: v1.FindParticipatingProjectsRequest
	(*FindParticipatingTenantsRequest)(nil),   // 1: v1.FindParticipatingTenantsRequest
	(*ListTenantMembersRequest)(nil),          // 2: v1.ListTenantMembersRequest
	(*ListTenantMembersResponse)(nil),         // 3: v1.ListTenantMembersResponse
	(*FindParticipatingProjectsResponse)(nil), // 4: v1.FindParticipatingProjectsResponse
	(*FindParticipatingTenantsResponse)(nil),  // 5: v1.FindParticipatingTenantsResponse
	(*ProjectWithMembershipAnnotations)(nil),  // 6: v1.ProjectWithMembershipAnnotations
	(*TenantWithMembershipAnnotations)(nil),   // 7: v1.TenantWithMembershipAnnotations
	(*Tenant)(nil),                            // 8: v1.Tenant
	(*TenantCreateRequest)(nil),               // 9: v1.TenantCreateRequest
	(*TenantUpdateRequest)(nil),               // 10: v1.TenantUpdateRequest
	(*TenantDeleteRequest)(nil),               // 11: v1.TenantDeleteRequest
	(*TenantGetRequest)(nil),                  // 12: v1.TenantGetRequest
	(*TenantGetHistoryRequest)(nil),           // 13: v1.TenantGetHistoryRequest
	(*TenantFindRequest)(nil),                 // 14: v1.TenantFindRequest
	(*TenantResponse)(nil),                    // 15: v1.TenantResponse
	(*TenantListResponse)(nil),                // 16: v1.TenantListResponse
	(*PaymentDetails)(nil),                    // 17: v1.PaymentDetails
	(*ContactDetails)(nil),                    // 18: v1.ContactDetails
	nil,                                       // 19: v1.ProjectWithMembershipAnnotations.ProjectAnnotationsEntry
	nil,                                       // 20: v1.ProjectWithMembershipAnnotations.TenantAnnotationsEntry
	nil,                                       // 21: v1.TenantWithMembershipAnnotations.ProjectAnnotationsEntry
	nil,                                       // 22: v1.TenantWithMembershipAnnotations.TenantAnnotationsEntry
	nil,                                       // 23: v1.TenantFindRequest.AnnotationsEntry
	nil,                                       // 24: v1.PaymentDetails.DetailsEntry
	nil,                                       // 25: v1.PaymentDetails.AnnotationsEntry
	nil,                                       // 26: v1.ContactDetails.AnnotationsEntry
	(*Project)(nil),                           // 27: v1.Project
	(*Meta)(nil),                              // 28: v1.Meta
	(*QuotaSet)(nil),                          // 29: v1.QuotaSet
	(*IAMConfig)(nil),                         // 30: v1.IAMConfig
	(*timestamppb.Timestamp)(nil),             // 31: google.protobuf.Timestamp
	(*Paging)(nil),                            // 32: v1.Paging
	(*_type.PostalAddress)(nil),               // 33: google.type.PostalAddress
}
var file_v1_tenant_proto_depIdxs = []int32{
	7,  // 0: v1.ListTenantMembersResponse.tenants:type_name -> v1.TenantWithMembershipAnnotations
	6,  // 1: v1.FindParticipatingProjectsResponse.projects:type_name -> v1.ProjectWithMembershipAnnotations
	7,  // 2: v1.FindParticipatingTenantsResponse.tenants:type_name -> v1.TenantWithMembershipAnnotations
	27, // 3: v1.ProjectWithMembershipAnnotations.project:type_name -> v1.Project
	19, // 4: v1.ProjectWithMembershipAnnotations.project_annotations:type_name -> v1.ProjectWithMembershipAnnotations.ProjectAnnotationsEntry
	20, // 5: v1.ProjectWithMembershipAnnotations.tenant_annotations:type_name -> v1.ProjectWithMembershipAnnotations.TenantAnnotationsEntry
	8,  // 6: v1.TenantWithMembershipAnnotations.tenant:type_name -> v1.Tenant
	21, // 7: v1.TenantWithMembershipAnnotations.project_annotations:type_name -> v1.TenantWithMembershipAnnotations.ProjectAnnotationsEntry
	22, // 8: v1.TenantWithMembershipAnnotations.tenant_annotations:type_name -> v1.TenantWithMembershipAnnotations.TenantAnnotationsEntry
	28, // 9: v1.Tenant.meta:type_name -> v1.Meta
	29, // 10: v1.Tenant.default_quotas:type_name -> v1.QuotaSet
	29, // 11: v1.Tenant.quotas:type_name -> v1.QuotaSet
	30, // 12: v1.Tenant.iam_config:type_name -> v1.IAMConfig
	17, // 13: v1.Tenant.payment:type_name -> v1.PaymentDetails
	18, // 14: v1.Tenant.contact_details:type_name -> v1.ContactDetails
	8,  // 15: v1.TenantCreateRequest.tenant:type_name -> v1.Tenant
	8,  // 16: v1.TenantUpdateRequest.tenant:type_name -> v1.Tenant
	31, // 17: v1.TenantGetHistoryRequest.at:type_name -> google.protobuf.Timestamp
	32, // 18: v1.TenantFindRequest.paging:type_name -> v1.Paging
	23, // 19: v1.TenantFindRequest.annotations:type_name -> v1.TenantFindRequest.AnnotationsEntry
	8,  // 20: v1.TenantResponse.tenant:type_name -> v1.Tenant
	8,  // 21: v1.TenantListResponse.tenants:type_name -> v1.Tenant
	24, // 22: v1.PaymentDetails.details:type_name -> v1.PaymentDetails.DetailsEntry
	25, // 23: v1.PaymentDetails.annotations:type_name -> v1.PaymentDetails.AnnotationsEntry
	33, // 24: v1.ContactDetails.address:type_name -> google.type.PostalAddress
	26, // 25: v1.ContactDetails.annotations:type_name -> v1.ContactDetails.AnnotationsEntry
	9,  // 26: v1.TenantService.Create:input_type -> v1.TenantCreateRequest
	10, // 27: v1.TenantService.Update:input_type -> v1.TenantUpdateRequest
	11, // 28: v1.TenantService.Delete:input_type -> v1.TenantDeleteRequest
	12, // 29: v1.TenantService.Get:input_type -> v1.TenantGetRequest
	13, // 30: v1.TenantService.GetHistory:input_type -> v1.TenantGetHistoryRequest
	14, // 31: v1.TenantService.Find:input_type -> v1.TenantFindRequest
	2,  // 32: v1.TenantService.ListTenantMembers:input_type -> v1.ListTenantMembersRequest
	0,  // 33: v1.TenantService.FindParticipatingProjects:input_type -> v1.FindParticipatingProjectsRequest
	1,  // 34: v1.TenantService.FindParticipatingTenants:input_type -> v1.FindParticipatingTenantsRequest
	15, // 35: v1.TenantService.Create:output_type -> v1.TenantResponse
	15, // 36: v1.TenantService.Update:output_type -> v1.TenantResponse
	15, // 37: v1.TenantService.Delete:output_type -> v1.TenantResponse
	15, // 38: v1.TenantService.Get:output_type -> v1.TenantResponse
	15, // 39: v1.TenantService.GetHistory:output_type -> v1.TenantResponse
	16, // 40: v1.TenantService.Find:output_type -> v1.TenantListResponse
	3,  // 41: v1.TenantService.ListTenantMembers:output_type -> v1.ListTenantMembersResponse
	4,  // 42: v1.TenantService.FindParticipatingProjects:output_type -> v1.FindParticipatingProjectsResponse
	5,  // 43: v1.TenantService.FindParticipatingTenants:output_type -> v1.FindParticipatingTenantsResponse
	35, // [35:44] is the sub-list for method output_type
	26, // [26:35] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_v1_tenant_proto_init() }
func file_v1_tenant_proto_init() {
	if File_v1_tenant_proto != nil {
		return
	}
	file_v1_common_proto_init()
	file_v1_iam_proto_init()
	file_v1_meta_proto_init()
	file_v1_project_proto_init()
	file_v1_quota_proto_init()
	file_v1_tenant_proto_msgTypes[0].OneofWrappers = []any{}
	file_v1_tenant_proto_msgTypes[1].OneofWrappers = []any{}
	file_v1_tenant_proto_msgTypes[2].OneofWrappers = []any{}
	file_v1_tenant_proto_msgTypes[14].OneofWrappers = []any{}
	file_v1_tenant_proto_msgTypes[16].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_tenant_proto_rawDesc), len(file_v1_tenant_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_tenant_proto_goTypes,
		DependencyIndexes: file_v1_tenant_proto_depIdxs,
		MessageInfos:      file_v1_tenant_proto_msgTypes,
	}.Build()
	File_v1_tenant_proto = out.File
	file_v1_tenant_proto_goTypes = nil
	file_v1_tenant_proto_depIdxs = nil
}
