// This file was automatically generated by pkg/gen/genscanvaluer.
// DO NOT EDIT MANUALLY.
// Regenerate with "go generate" or "make generate"

package apiv1

import (
	"database/sql/driver"
	"fmt"
)

func (t *TenantMember) Schema() string {
	return `
	CREATE TABLE IF NOT EXISTS tenantmembers (
		id   text PRIMARY KEY NOT NULL,
		tenantmember JSONB NOT NULL
	);
	CREATE INDEX IF NOT EXISTS tenantmember_idx ON tenantmembers USING GIN(tenantmember);

	CREATE TABLE IF NOT EXISTS tenantmembers_history (
		id         text NOT NULL,
		op         char NOT NULL,
		created_at timestamptz NOT NULL,
		tenantmember JSONB NOT NULL
	);
	CREATE INDEX IF NOT EXISTS tenantmembers_history_id_created_at_idx ON tenantmembers_history USING btree(id, created_at);
`
}

func (t *TenantMember) JSONField() string {
	return "tenantmember"
}

func (t *TenantMember) TableName() string {
	return "tenantmembers"
}

func (t *TenantMember) Kind() string {
	return "TenantMember"
}

func (t *TenantMember) APIVersion() string {
	return "apiv1"
}

// Value make the TenantMember struct implement the driver.Valuer interface. This method
// simply returns the JSON-encoded representation of the struct.
func (t *TenantMember) Value() (driver.Value, error) {
	return json.Marshal(t)
}

// Scan make the TenantMember struct implement the sql.Scanner interface. This method
// simply decodes a JSON-encoded value into the struct fields.
func (t *TenantMember) Scan(value any) error {
	b, ok := value.([]byte)
	if !ok {
		return fmt.Errorf("type assertion to []byte failed")
	}

	err := json.Unmarshal(b, t)
	return err
}
