// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/metal-stack/masterdata-api/api/v1"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockProjectMemberServiceClient creates a new instance of MockProjectMemberServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProjectMemberServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProjectMemberServiceClient {
	mock := &MockProjectMemberServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProjectMemberServiceClient is an autogenerated mock type for the ProjectMemberServiceClient type
type MockProjectMemberServiceClient struct {
	mock.Mock
}

type MockProjectMemberServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProjectMemberServiceClient) EXPECT() *MockProjectMemberServiceClient_Expecter {
	return &MockProjectMemberServiceClient_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockProjectMemberServiceClient
func (_mock *MockProjectMemberServiceClient) Create(ctx context.Context, in *v1.ProjectMemberCreateRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *v1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberCreateRequest, ...grpc.CallOption) (*v1.ProjectMemberResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberCreateRequest, ...grpc.CallOption) *v1.ProjectMemberResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ProjectMemberCreateRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectMemberServiceClient_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProjectMemberServiceClient_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ProjectMemberCreateRequest
//   - opts ...grpc.CallOption
func (_e *MockProjectMemberServiceClient_Expecter) Create(ctx interface{}, in interface{}, opts ...interface{}) *MockProjectMemberServiceClient_Create_Call {
	return &MockProjectMemberServiceClient_Create_Call{Call: _e.mock.On("Create",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProjectMemberServiceClient_Create_Call) Run(run func(ctx context.Context, in *v1.ProjectMemberCreateRequest, opts ...grpc.CallOption)) *MockProjectMemberServiceClient_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ProjectMemberCreateRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ProjectMemberCreateRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProjectMemberServiceClient_Create_Call) Return(projectMemberResponse *v1.ProjectMemberResponse, err error) *MockProjectMemberServiceClient_Create_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *MockProjectMemberServiceClient_Create_Call) RunAndReturn(run func(ctx context.Context, in *v1.ProjectMemberCreateRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error)) *MockProjectMemberServiceClient_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockProjectMemberServiceClient
func (_mock *MockProjectMemberServiceClient) Delete(ctx context.Context, in *v1.ProjectMemberDeleteRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 *v1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberDeleteRequest, ...grpc.CallOption) (*v1.ProjectMemberResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberDeleteRequest, ...grpc.CallOption) *v1.ProjectMemberResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ProjectMemberDeleteRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectMemberServiceClient_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProjectMemberServiceClient_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ProjectMemberDeleteRequest
//   - opts ...grpc.CallOption
func (_e *MockProjectMemberServiceClient_Expecter) Delete(ctx interface{}, in interface{}, opts ...interface{}) *MockProjectMemberServiceClient_Delete_Call {
	return &MockProjectMemberServiceClient_Delete_Call{Call: _e.mock.On("Delete",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProjectMemberServiceClient_Delete_Call) Run(run func(ctx context.Context, in *v1.ProjectMemberDeleteRequest, opts ...grpc.CallOption)) *MockProjectMemberServiceClient_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ProjectMemberDeleteRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ProjectMemberDeleteRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProjectMemberServiceClient_Delete_Call) Return(projectMemberResponse *v1.ProjectMemberResponse, err error) *MockProjectMemberServiceClient_Delete_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *MockProjectMemberServiceClient_Delete_Call) RunAndReturn(run func(ctx context.Context, in *v1.ProjectMemberDeleteRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error)) *MockProjectMemberServiceClient_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockProjectMemberServiceClient
func (_mock *MockProjectMemberServiceClient) Find(ctx context.Context, in *v1.ProjectMemberFindRequest, opts ...grpc.CallOption) (*v1.ProjectMemberListResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *v1.ProjectMemberListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberFindRequest, ...grpc.CallOption) (*v1.ProjectMemberListResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberFindRequest, ...grpc.CallOption) *v1.ProjectMemberListResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProjectMemberListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ProjectMemberFindRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectMemberServiceClient_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockProjectMemberServiceClient_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ProjectMemberFindRequest
//   - opts ...grpc.CallOption
func (_e *MockProjectMemberServiceClient_Expecter) Find(ctx interface{}, in interface{}, opts ...interface{}) *MockProjectMemberServiceClient_Find_Call {
	return &MockProjectMemberServiceClient_Find_Call{Call: _e.mock.On("Find",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProjectMemberServiceClient_Find_Call) Run(run func(ctx context.Context, in *v1.ProjectMemberFindRequest, opts ...grpc.CallOption)) *MockProjectMemberServiceClient_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ProjectMemberFindRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ProjectMemberFindRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProjectMemberServiceClient_Find_Call) Return(projectMemberListResponse *v1.ProjectMemberListResponse, err error) *MockProjectMemberServiceClient_Find_Call {
	_c.Call.Return(projectMemberListResponse, err)
	return _c
}

func (_c *MockProjectMemberServiceClient_Find_Call) RunAndReturn(run func(ctx context.Context, in *v1.ProjectMemberFindRequest, opts ...grpc.CallOption) (*v1.ProjectMemberListResponse, error)) *MockProjectMemberServiceClient_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockProjectMemberServiceClient
func (_mock *MockProjectMemberServiceClient) Get(ctx context.Context, in *v1.ProjectMemberGetRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *v1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberGetRequest, ...grpc.CallOption) (*v1.ProjectMemberResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberGetRequest, ...grpc.CallOption) *v1.ProjectMemberResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ProjectMemberGetRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectMemberServiceClient_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockProjectMemberServiceClient_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ProjectMemberGetRequest
//   - opts ...grpc.CallOption
func (_e *MockProjectMemberServiceClient_Expecter) Get(ctx interface{}, in interface{}, opts ...interface{}) *MockProjectMemberServiceClient_Get_Call {
	return &MockProjectMemberServiceClient_Get_Call{Call: _e.mock.On("Get",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProjectMemberServiceClient_Get_Call) Run(run func(ctx context.Context, in *v1.ProjectMemberGetRequest, opts ...grpc.CallOption)) *MockProjectMemberServiceClient_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ProjectMemberGetRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ProjectMemberGetRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProjectMemberServiceClient_Get_Call) Return(projectMemberResponse *v1.ProjectMemberResponse, err error) *MockProjectMemberServiceClient_Get_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *MockProjectMemberServiceClient_Get_Call) RunAndReturn(run func(ctx context.Context, in *v1.ProjectMemberGetRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error)) *MockProjectMemberServiceClient_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockProjectMemberServiceClient
func (_mock *MockProjectMemberServiceClient) Update(ctx context.Context, in *v1.ProjectMemberUpdateRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, in, opts)
	} else {
		tmpRet = _mock.Called(ctx, in)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *v1.ProjectMemberResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberUpdateRequest, ...grpc.CallOption) (*v1.ProjectMemberResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.ProjectMemberUpdateRequest, ...grpc.CallOption) *v1.ProjectMemberResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.ProjectMemberResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *v1.ProjectMemberUpdateRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProjectMemberServiceClient_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProjectMemberServiceClient_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - in *v1.ProjectMemberUpdateRequest
//   - opts ...grpc.CallOption
func (_e *MockProjectMemberServiceClient_Expecter) Update(ctx interface{}, in interface{}, opts ...interface{}) *MockProjectMemberServiceClient_Update_Call {
	return &MockProjectMemberServiceClient_Update_Call{Call: _e.mock.On("Update",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockProjectMemberServiceClient_Update_Call) Run(run func(ctx context.Context, in *v1.ProjectMemberUpdateRequest, opts ...grpc.CallOption)) *MockProjectMemberServiceClient_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.ProjectMemberUpdateRequest
		if args[1] != nil {
			arg1 = args[1].(*v1.ProjectMemberUpdateRequest)
		}
		var arg2 []grpc.CallOption
		var variadicArgs []grpc.CallOption
		if len(args) > 2 {
			variadicArgs = args[2].([]grpc.CallOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockProjectMemberServiceClient_Update_Call) Return(projectMemberResponse *v1.ProjectMemberResponse, err error) *MockProjectMemberServiceClient_Update_Call {
	_c.Call.Return(projectMemberResponse, err)
	return _c
}

func (_c *MockProjectMemberServiceClient_Update_Call) RunAndReturn(run func(ctx context.Context, in *v1.ProjectMemberUpdateRequest, opts ...grpc.CallOption) (*v1.ProjectMemberResponse, error)) *MockProjectMemberServiceClient_Update_Call {
	_c.Call.Return(run)
	return _c
}
