// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsafeProjectServiceServer creates a new instance of MockUnsafeProjectServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeProjectServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeProjectServiceServer {
	mock := &MockUnsafeProjectServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeProjectServiceServer is an autogenerated mock type for the UnsafeProjectServiceServer type
type MockUnsafeProjectServiceServer struct {
	mock.Mock
}

type MockUnsafeProjectServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeProjectServiceServer) EXPECT() *MockUnsafeProjectServiceServer_Expecter {
	return &MockUnsafeProjectServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedProjectServiceServer provides a mock function for the type MockUnsafeProjectServiceServer
func (_mock *MockUnsafeProjectServiceServer) mustEmbedUnimplementedProjectServiceServer() {
	_mock.Called()
	return
}

// MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedProjectServiceServer'
type MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedProjectServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeProjectServiceServer_Expecter) mustEmbedUnimplementedProjectServiceServer() *MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call {
	return &MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedProjectServiceServer")}
}

func (_c *MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call) Run(run func()) *MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call) Return() *MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call) RunAndReturn(run func()) *MockUnsafeProjectServiceServer_mustEmbedUnimplementedProjectServiceServer_Call {
	_c.Run(run)
	return _c
}
