// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnsafeProjectMemberServiceServer creates a new instance of MockUnsafeProjectMemberServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeProjectMemberServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeProjectMemberServiceServer {
	mock := &MockUnsafeProjectMemberServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnsafeProjectMemberServiceServer is an autogenerated mock type for the UnsafeProjectMemberServiceServer type
type MockUnsafeProjectMemberServiceServer struct {
	mock.Mock
}

type MockUnsafeProjectMemberServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeProjectMemberServiceServer) EXPECT() *MockUnsafeProjectMemberServiceServer_Expecter {
	return &MockUnsafeProjectMemberServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedProjectMemberServiceServer provides a mock function for the type MockUnsafeProjectMemberServiceServer
func (_mock *MockUnsafeProjectMemberServiceServer) mustEmbedUnimplementedProjectMemberServiceServer() {
	_mock.Called()
	return
}

// MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedProjectMemberServiceServer'
type MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedProjectMemberServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeProjectMemberServiceServer_Expecter) mustEmbedUnimplementedProjectMemberServiceServer() *MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call {
	return &MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedProjectMemberServiceServer")}
}

func (_c *MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call) Run(run func()) *MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call) Return() *MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call) RunAndReturn(run func()) *MockUnsafeProjectMemberServiceServer_mustEmbedUnimplementedProjectMemberServiceServer_Call {
	_c.Run(run)
	return _c
}
