// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/project.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/metal-stack/masterdata-api/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProjectServiceName is the fully-qualified name of the ProjectService service.
	ProjectServiceName = "api.v1.ProjectService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProjectServiceCreateProcedure is the fully-qualified name of the ProjectService's Create RPC.
	ProjectServiceCreateProcedure = "/api.v1.ProjectService/Create"
	// ProjectServiceUpdateProcedure is the fully-qualified name of the ProjectService's Update RPC.
	ProjectServiceUpdateProcedure = "/api.v1.ProjectService/Update"
	// ProjectServiceDeleteProcedure is the fully-qualified name of the ProjectService's Delete RPC.
	ProjectServiceDeleteProcedure = "/api.v1.ProjectService/Delete"
	// ProjectServiceGetProcedure is the fully-qualified name of the ProjectService's Get RPC.
	ProjectServiceGetProcedure = "/api.v1.ProjectService/Get"
	// ProjectServiceGetHistoryProcedure is the fully-qualified name of the ProjectService's GetHistory
	// RPC.
	ProjectServiceGetHistoryProcedure = "/api.v1.ProjectService/GetHistory"
	// ProjectServiceFindProcedure is the fully-qualified name of the ProjectService's Find RPC.
	ProjectServiceFindProcedure = "/api.v1.ProjectService/Find"
)

// ProjectServiceClient is a client for the api.v1.ProjectService service.
type ProjectServiceClient interface {
	Create(context.Context, *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectResponse], error)
	Update(context.Context, *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectResponse], error)
	Delete(context.Context, *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectResponse], error)
	Get(context.Context, *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectResponse], error)
	GetHistory(context.Context, *connect.Request[v1.ProjectGetHistoryRequest]) (*connect.Response[v1.ProjectResponse], error)
	Find(context.Context, *connect.Request[v1.ProjectFindRequest]) (*connect.Response[v1.ProjectListResponse], error)
}

// NewProjectServiceClient constructs a client for the api.v1.ProjectService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProjectServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProjectServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	projectServiceMethods := v1.File_api_v1_project_proto.Services().ByName("ProjectService").Methods()
	return &projectServiceClient{
		create: connect.NewClient[v1.ProjectCreateRequest, v1.ProjectResponse](
			httpClient,
			baseURL+ProjectServiceCreateProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Create")),
			connect.WithClientOptions(opts...),
		),
		update: connect.NewClient[v1.ProjectUpdateRequest, v1.ProjectResponse](
			httpClient,
			baseURL+ProjectServiceUpdateProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
		delete: connect.NewClient[v1.ProjectDeleteRequest, v1.ProjectResponse](
			httpClient,
			baseURL+ProjectServiceDeleteProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Delete")),
			connect.WithClientOptions(opts...),
		),
		get: connect.NewClient[v1.ProjectGetRequest, v1.ProjectResponse](
			httpClient,
			baseURL+ProjectServiceGetProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Get")),
			connect.WithClientOptions(opts...),
		),
		getHistory: connect.NewClient[v1.ProjectGetHistoryRequest, v1.ProjectResponse](
			httpClient,
			baseURL+ProjectServiceGetHistoryProcedure,
			connect.WithSchema(projectServiceMethods.ByName("GetHistory")),
			connect.WithClientOptions(opts...),
		),
		find: connect.NewClient[v1.ProjectFindRequest, v1.ProjectListResponse](
			httpClient,
			baseURL+ProjectServiceFindProcedure,
			connect.WithSchema(projectServiceMethods.ByName("Find")),
			connect.WithClientOptions(opts...),
		),
	}
}

// projectServiceClient implements ProjectServiceClient.
type projectServiceClient struct {
	create     *connect.Client[v1.ProjectCreateRequest, v1.ProjectResponse]
	update     *connect.Client[v1.ProjectUpdateRequest, v1.ProjectResponse]
	delete     *connect.Client[v1.ProjectDeleteRequest, v1.ProjectResponse]
	get        *connect.Client[v1.ProjectGetRequest, v1.ProjectResponse]
	getHistory *connect.Client[v1.ProjectGetHistoryRequest, v1.ProjectResponse]
	find       *connect.Client[v1.ProjectFindRequest, v1.ProjectListResponse]
}

// Create calls api.v1.ProjectService.Create.
func (c *projectServiceClient) Create(ctx context.Context, req *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return c.create.CallUnary(ctx, req)
}

// Update calls api.v1.ProjectService.Update.
func (c *projectServiceClient) Update(ctx context.Context, req *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return c.update.CallUnary(ctx, req)
}

// Delete calls api.v1.ProjectService.Delete.
func (c *projectServiceClient) Delete(ctx context.Context, req *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return c.delete.CallUnary(ctx, req)
}

// Get calls api.v1.ProjectService.Get.
func (c *projectServiceClient) Get(ctx context.Context, req *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return c.get.CallUnary(ctx, req)
}

// GetHistory calls api.v1.ProjectService.GetHistory.
func (c *projectServiceClient) GetHistory(ctx context.Context, req *connect.Request[v1.ProjectGetHistoryRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return c.getHistory.CallUnary(ctx, req)
}

// Find calls api.v1.ProjectService.Find.
func (c *projectServiceClient) Find(ctx context.Context, req *connect.Request[v1.ProjectFindRequest]) (*connect.Response[v1.ProjectListResponse], error) {
	return c.find.CallUnary(ctx, req)
}

// ProjectServiceHandler is an implementation of the api.v1.ProjectService service.
type ProjectServiceHandler interface {
	Create(context.Context, *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectResponse], error)
	Update(context.Context, *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectResponse], error)
	Delete(context.Context, *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectResponse], error)
	Get(context.Context, *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectResponse], error)
	GetHistory(context.Context, *connect.Request[v1.ProjectGetHistoryRequest]) (*connect.Response[v1.ProjectResponse], error)
	Find(context.Context, *connect.Request[v1.ProjectFindRequest]) (*connect.Response[v1.ProjectListResponse], error)
}

// NewProjectServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProjectServiceHandler(svc ProjectServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	projectServiceMethods := v1.File_api_v1_project_proto.Services().ByName("ProjectService").Methods()
	projectServiceCreateHandler := connect.NewUnaryHandler(
		ProjectServiceCreateProcedure,
		svc.Create,
		connect.WithSchema(projectServiceMethods.ByName("Create")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceUpdateHandler := connect.NewUnaryHandler(
		ProjectServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(projectServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceDeleteHandler := connect.NewUnaryHandler(
		ProjectServiceDeleteProcedure,
		svc.Delete,
		connect.WithSchema(projectServiceMethods.ByName("Delete")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetHandler := connect.NewUnaryHandler(
		ProjectServiceGetProcedure,
		svc.Get,
		connect.WithSchema(projectServiceMethods.ByName("Get")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceGetHistoryHandler := connect.NewUnaryHandler(
		ProjectServiceGetHistoryProcedure,
		svc.GetHistory,
		connect.WithSchema(projectServiceMethods.ByName("GetHistory")),
		connect.WithHandlerOptions(opts...),
	)
	projectServiceFindHandler := connect.NewUnaryHandler(
		ProjectServiceFindProcedure,
		svc.Find,
		connect.WithSchema(projectServiceMethods.ByName("Find")),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.ProjectService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProjectServiceCreateProcedure:
			projectServiceCreateHandler.ServeHTTP(w, r)
		case ProjectServiceUpdateProcedure:
			projectServiceUpdateHandler.ServeHTTP(w, r)
		case ProjectServiceDeleteProcedure:
			projectServiceDeleteHandler.ServeHTTP(w, r)
		case ProjectServiceGetProcedure:
			projectServiceGetHandler.ServeHTTP(w, r)
		case ProjectServiceGetHistoryProcedure:
			projectServiceGetHistoryHandler.ServeHTTP(w, r)
		case ProjectServiceFindProcedure:
			projectServiceFindHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProjectServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProjectServiceHandler struct{}

func (UnimplementedProjectServiceHandler) Create(context.Context, *connect.Request[v1.ProjectCreateRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ProjectService.Create is not implemented"))
}

func (UnimplementedProjectServiceHandler) Update(context.Context, *connect.Request[v1.ProjectUpdateRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ProjectService.Update is not implemented"))
}

func (UnimplementedProjectServiceHandler) Delete(context.Context, *connect.Request[v1.ProjectDeleteRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ProjectService.Delete is not implemented"))
}

func (UnimplementedProjectServiceHandler) Get(context.Context, *connect.Request[v1.ProjectGetRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ProjectService.Get is not implemented"))
}

func (UnimplementedProjectServiceHandler) GetHistory(context.Context, *connect.Request[v1.ProjectGetHistoryRequest]) (*connect.Response[v1.ProjectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ProjectService.GetHistory is not implemented"))
}

func (UnimplementedProjectServiceHandler) Find(context.Context, *connect.Request[v1.ProjectFindRequest]) (*connect.Response[v1.ProjectListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.ProjectService.Find is not implemented"))
}
