name: Build image from pull request

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Lint
      uses: actions-contrib/golangci-lint@master
      with:
        args: run
    - name: Build and push Docker image
      run: |
        docker login -u ${{ secrets.DOCKER_HUB_USER }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -t metalstack/masterdata-api:pr-${GITHUB_HEAD_REF##*/} .
        docker push metalstack/masterdata-api:pr-${GITHUB_HEAD_REF##*/}
